### ISSUE TITLE
Slow performance with huge query results on items-method

### ISSUE THREAD

**Issue by drmendozaz** [guylabs/ion-autocomplete#1]
I recommend using collection-repeat instead of ng-repeat for this cases:

http://ionicframework.com/docs/api/directive/collectionRepeat/

**Comment by guylabs** [comment]
Hi Daniel,

yes that is true. Thanks for the hint! I just changed it but now I need to adapt some end to end tests and then I will release it as part of version 0.2.0. I hope I can finish it this week.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
I couldn't swith the selectedItems `ng-repeat` as there were UI issues when there were two `collection-repeat`'s in one `ion-content`. The other `ng-repeat` I changed to a `collection-repeat` and everything looks fine. Can you please test it with the current master such that I can close the issue and then release the 0.2.0 on Sunday?

Thanks and regards,

Guy

**Comment by drmendozaz** [comment]
I've just tested it and it works pretty well like that.
And that's correct, It's not necessary to change the first ng-repeat.

Thank you very much! And congrats for the amazing component!

Daniel

**Comment by guylabs** [comment]
Thanks a lot for you pointing this out and testing it!

Regards,

Guy
