### ISSUE TITLE
Inadvertantly opens while scrolling

### ISSUE THREAD

**Issue by texh** [guylabs/ion-autocomplete#10]
If a user scrolls their view and the touch started upon an autocomplete field the autocomplete modal will show even if field is no longer in view.

This is a duplicate of closed israelidanny#2, though I think I've found a workaround. Not sure if you'd want to make this configurable as it may cause unexpected side effects for users who are already expecting this behaviour.

**Comment by guylabs** [comment]
Thanks again for the contribution! Nice workaround and I think it's not needed to be able to configure this as the old way is hopefully never the wanted behaviour. And if there are users which need to configure it, then I'll add it.
