### ISSUE TITLE
Preseted value doesnt appear in dropdown

### ISSUE THREAD

**Issue by Kopleman** [guylabs/ion-autocomplete#100]
Well the whole behavior of derective is strange. Test case: we have form with autocompleate and we already have  value. If we use ng-model it will appear in input but wount appear in popup as selected(no matter what format it has).

**Comment by guylabs** [comment]
Hi,

please use the master version of the directive with the following properties set:

* https://github.com/guylabs/ion-autocomplete#external-model
* https://github.com/guylabs/ion-autocomplete#the-model-to-item-method

Then you are able to prepopulate the selected items.

Thanks and regards,

Guy

**Comment by Kopleman** [comment]
Yea, thank you, but I've found bug with this approach: A function that used in `items-clicked-method` triggers on render(probably same behaviour for others action `-method`s, I havent checked )

**Comment by guylabs** [comment]
Yes that is true this will get called as internally it will call the `selectItem` method which then selects the items from the `externalModel` and then it also calls the `items-clicked-method`. Does this affect the logic in you `items-clicked-method` or can we leave it as it is?

**Comment by Kopleman** [comment]
No Its ok. Sorry for another question: Is there any way to show default search results every time when user opens a search-form? I noticed `search-items` but it works only on first launch.

**Comment by guylabs** [comment]
Hi,

ok good then I will close the issue. And about your other question: you can have a look at this comment https://github.com/guylabs/ion-autocomplete/issues/57#issuecomment-153834706 and check the new functionality in the branch as this will be the way to prepopulate the search items. If you have questions please add a comment there.

Thanks and regards,

Guy
