### ISSUE TITLE
Cannot scrolldown to the end of the list when keyboard in open

### ISSUE THREAD

**Issue by touletan** [guylabs/ion-autocomplete#101]
Hi,
When the keyboard is displayed, I don't have access to the latest items of the list. I have to close the keyboard first (testing with Iphone). Is there a way to increase the size of the component, so we can scroll down until the end of the list when keyboard is displayed?

**Comment by guylabs** [comment]
Hi,

could you maybe create a small test with an empty view with a standard ionic collection repeat and test again if it this also happens? So without the `ion-autocomplete` component just with plain Ionic. If this also happens there then it is an Ionic issue and then please create an issue at their issue tracker.

Thanks and regards,

Guy

**Comment by touletan** [comment]
some behavior with ionic collection. This one can be closed.

**Comment by waleedasif322** [comment]
@touletan did you figure out a fix for this?

**Comment by olivbd** [comment]
@touletan can you explain us how did you fix this?

**Comment by olivbd** [comment]
@touletan can you explain us how did you fix this?

**Comment by touletan** [comment]
It has not been fixed. We still have to close the keyboard to see the end of the list.

________________________________
De : olivbd <notifications@github.com>
Envoyé : 24 octobre 2016 15:44
À : guylabs/ion-autocomplete
Cc : touletan; Mention
Objet : Re: [guylabs/ion-autocomplete] Cannot scrolldown to the end of the list when keyboard in open (#101)


@touletan<https://github.com/touletan> can you explain us how did you fix this?

-
