### ISSUE TITLE
issue with search-items

### ISSUE THREAD

**Issue by touletan** [guylabs/ion-autocomplete#104]
Hi, I'm having issue with Search-items functionality. I'm not able to pre populated the list of value when the modal is opening.
  <input name="procedure"
                         ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete text-right " autocomplete="off"
                         ng-model="newlog.procedure"
                         search-items="prepopulatedProcedures"
                         item-value-key="$id"
                         item-view-value-key="$id"
                         items-method="getProcedures(query)"
                         items-method-value-key="items"
                         max-selected-items="5"
                         external-model="selected.items"
                         items-clicked-method="changedProcedure(callback)"
                         items-removed-method="changedProcedure(callback)"
                         required />

and
$scope.prepopulatedProcedures looks like this:
[ {$id:test, $value:fdasfdsa},{.....}]

What am I doing wrong?

Also is there a way to simply call items-method function when modal is opening and prepopulate the list that way 
if (query) { return filtered normal list } else  { return prepopulated list }
Its easier that way and no need for a Search-items functionality.

Merci/Danke

**Comment by guylabs** [comment]
Hi,

please have a look at the #57 as there I will remove the `search-items` again and do it the way you mentioned. Please follow this issue and add your comments there.

Thanks and regards,

Guy

**Comment by touletan** [comment]
thank you; it seems that someone had that idea before me :)
