### ISSUE TITLE
Mismatch attribute  externally-managed in documentation

### ISSUE THREAD

**Issue by yonsonsal** [guylabs/ion-autocomplete#105]
I'm trying to externally manage the behaviour of autocomplete with externally-managed="true" but it doesn't work .Looking at the code I realized that in line 58 
this.manageExternally = valueOrDefault($attrs.manageExternally, "false"); 
the attribute is should be  be named  "manage-externally". I'm using the new one but I don't know which is the correct in future releases.

**Comment by guylabs** [comment]
Hi @yonsonsal,

thanks a lot for catching this issue in the documentation. I just updated it and now it should be ok.

Thanks and regards,

Guy
