### ISSUE TITLE
Strict Dependency Injection Fails in Version 0.3.0

### ISSUE THREAD

**Issue by edmondchui** [guylabs/ion-autocomplete#106]
I got the following error with version 0.3.0

```js
"Error: [$injector:strictdi] function($attrs) is not using explicit annotation and cannot be invoked in strict mode
```

**Comment by edmondchui** [comment]
Looks like the issue if fixed on the master. When will be the next release?

**Comment by guylabs** [comment]
Hi @edmondchui,

I hope I can release it next week when all the other `0.3.1` issues are fixed and tested by the reporters.

Thanks and regards,

Guy
