### ISSUE TITLE
ion-autocomplete.min.js file causing errors

### ISSUE THREAD

**Issue by MoPHL** [guylabs/ion-autocomplete#107]
When the minified js file is used instead of the regular one, the error 

Error: [$injector:unpr] Unknown provider: aProvider <- a

is being thrown, using the non minified file fixes this issue.

**Comment by guylabs** [comment]
Hi Luís,

this has already been fixed on the master. See #95 for reference. The new version `0.3.1` will be released as soon as all other issues in the milestone are fixed too.

Thanks and regards,

Guy
