### ISSUE TITLE
template-url doesn't work with default template

### ISSUE THREAD

**Issue by yonsonsal** [guylabs/ion-autocomplete#108]
I'm trying to use my custom template and I started with the default template like says documentacion (https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L75) my example is here. http://plnkr.co/edit/Wkgjam?p=info
When trying to load the template at (https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L94)  get the following error:

Syntax Error: Token 'viewModel' is unexpected, expecting [)] at column 37 of the expression [viewModel.getItemValue(selectedItem viewModel.itemViewValueKey)] starting at [viewModel.itemViewValueKey].
Thanks!

**Comment by guylabs** [comment]
Hi,

I just updated the `template-url` documentation. Can you please have a look at it again and adapt your template?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @yonsonsal,

any news on this? As I want to release `0.3.1` this week.

Thanks and regards,

Guy

**Comment by yonsonsal** [comment]
Hi sorry I tohught I had alredy anwsered you but I had an error in github. The example is working properly now. Thanks!

**Comment by guylabs** [comment]
Ok nice!
