### ISSUE TITLE
template-url not working

### ISSUE THREAD

**Issue by typevitor** [guylabs/ion-autocomplete#111]
I need to customize a little the output format from the data, so i created a template and put into the code:

This is the input that contains the auto-complete

    <input class="ion-autocomplete col col-75" type="text" placeholder="DESCRIÇÃO"
                ng-model="produto.descrProduto" autocomplete="off"
                items-method="pesquisaDescricao(query)" max-selected-items="1"
                items-method-value-key="produto"
                item-view-value-key="[descProduto, codGrade, 
    precoPromocional ? precoPromocional : preco]"
                template-url="templates/pesquisa-descricao.html"
                items-clicked-method="addProdutoDesc(callback)"
                cancel-label="Cancelar"
                select-items-label="Selecione o produto..."
                ion-autocomplete readonly>
And the pesquisa-descricao template:

    <div class="ion-autocomplete-container modalDescricao">
      <div class="bar bar-header item-input-inset">
      <label class="item-input-wrapper">
      <i class="icon ion-search placeholder-icon"></i>
      <input type="search" class="ion-autocomplete-search"
              ng-model="viewModel.searchQuery" placeholder="descrição"/>
    </label>
    <div class="ion-autocomplete-loading-icon">
    </div>
      <button class="ion-autocomplete-cancel button button-clear">Cancelar</button>
    </div>
    <ion-content class="has-header">
      <ion-item class="item-divider" ng-if="viewModel.searchItems.length > 0">
        <span ng-bind="viewModel.selectItemsLabel"></span>
    </ion-item>
     <ion-item collection-repeat="item in viewModel.items"
    item-height="100px" item-width="100%" ng-click="viewModel.selectItem(item)">
      <span>Produto:
        <span ng-bind="viewModel.getItemValue(item, viewModel.itemViewValueKey)[0]"></span>
      </span>
      <br>
      <span ng-if="viewModel.getItemValue(item, viewModel.itemViewValueKey)[1] != '*'">Grade:
        <span ng-bind="viewModel.getItemValue(item, viewModel.itemViewValueKey)[1]"></span>
      </span>
      <br>
      <span>Preço:
        <span ng-bind="viewModel.getItemValue(item, viewModel.itemViewValueKey)[2] | currency : '' : 2">        </span>
      </span>
    </ion-item>
    </ion-content>
    </div>

The modal do not open. The overlay effect occurs, but only that. I know that have something to do with the display none/block for the modal. But i don't understand why isn't function normally or how i could manipulate that. I am missing something?

Thanks.

**Comment by typevitor** [comment]
The problem lies in the randomCssClass, as it not binding the elements correctly in a custom template (when it does not have the randomCssClass).
How it should work? Removing that class made the search appear, and it to works normally, but the cancel button still not works.

**Comment by guylabs** [comment]
Hi Vitor,

well this has already been discussed in several other issues. Can you have a look at this comment https://github.com/guylabs/ion-autocomplete/issues/74#issuecomment-146652629 and then this should work. I will close the issue as duplicate. If there is still an issue then please add it here.

Thanks and regards,

Guy
