### ISSUE TITLE
I should be able to define a latency in ms (milliseconds) before the search function is executed. 

### ISSUE THREAD

**Issue by assyme** [guylabs/ion-autocomplete#113]
It would be helpful if i can add a latency in milliseconds before the search is executed. Currently i want to avoid searching for every key pressed.

**Comment by guylabs** [comment]
Hi Asad, 

if you want to debounce the search you are able to use the `ng-model-options`. You need to use the master and you can check how to do it here: https://github.com/guylabs/ion-autocomplete#debouncing

With this you are able to exactly what you want.

Thanks and regards,

Guy
