### ISSUE TITLE
When maxSelectedItems is set to 1, selected items is still an array

### ISSUE THREAD

**Issue by rtorino** [guylabs/ion-autocomplete#115]
https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L150

**Comment by guylabs** [comment]
Hi Raymond,

I also wanted to change that once but now as you also need this I took the time to do it. Could you please test it with the master and tell me if it worked?

Thanks and regards,

Guy

**Comment by samuelsmal** [comment]
Hi there!

I am against this, or at least make it configurable. Otherwise a small change in the configuration has a too big impact on the rest of the application.

Best regards,
Sam

**Comment by guylabs** [comment]
Hi Sam,

sorry for my late reply but I was in vacations. Yes you are right with a configurable option it would be nicer. I will try to add it to the master before releasing a new version.

Thanks and regards,

Guy

**Comment by Hypher** [comment]
Against too. It is silly to change the *type* of `selectedItems` upon a change of the *number* of selectable items.
Better to provide a `singleSelection` option and a `selectedItem` (without s) property.

**Comment by guylabs** [comment]
Hi

I now added a `selectedItemsArray` property to the callback response which is always an array leaving the other functionality as it is.

This will be released in `0.3.3`.

Thanks and regards,

Guy
