### ISSUE TITLE
search/list form disabled after input click

### ISSUE THREAD

**Issue by germgerm** [guylabs/ion-autocomplete#118]
Using max-selected-items=1 ,when I click in the initial input I get the correct search/list form displayed BUT it is inaccessible due to the modal backdrop overlaying the entire form.
I resolved this by removing the following @ line 280 :

                    ionAutocompleteController.showModal = function () {
                        if (searchContainerDisplayed) {
                            return;
                        }
                        // show the backdrop and the search container
                        /**** $ionicBackdrop.retain();  <<== removed this line  ****/

This fix works, but is this a bug or am I doing something wrong ?

**Comment by guylabs** [comment]
Hi,

could you maybe try to reproduce it in a codepen? The end to end tests are all running fine and I also never had this issue. Can you please also tell me the versions of Ionic you are using and on what environment you are testing?

Thanks and regards,

Guy

**Comment by germgerm** [comment]
Hi Guy,
I will look at pulling this out into an isolated example - this is probably due to some interaction with another component.
ionic 1.1.1
this behaviour is consistent across both ripple ( VS2015 cordova )  & android 5.1.1 ( .apk )
no huge rush as commenting out that line resolves the issue

Gerry

**Comment by guylabs** [comment]
Hi Gerry,

ok nice. I just updated the master to `1.1.1` of Ionic but I still cannot reproduce the issue. Do you have any news on the isolated example?

Thanks and regards,

Guy

**Comment by germgerm** [comment]
Sorry - I have been working on another project -should get a chance to dig into this next week.

**Comment by guylabs** [comment]
Hi,

due to inactivity I will close the issue. If you still have any issues or remarks please add a comment or reopen the issue.

Thanks and regards,

Guy
