### ISSUE TITLE
Feature: Loading spinner

### ISSUE THREAD

**Issue by texh** [guylabs/ion-autocomplete#12]
Would be nice to be able to specify a loading icon/spinner for when the 'items-method' returns a method/promise for a potentially long-running action (ie. hitting a remote API vs local model).

Proposing an extra two configurable options:
```
<ion-autocomplete
  ...
  loader="true" [default to false for backwards compatibility]
  loader-icon="spinner"
  />
```
See http://ionicframework.com/docs/api/directive/ionSpinner/ for available icons.

**Comment by guylabs** [comment]
Hi Jarrod,

I just used your pull request and adapted the loading icon position and the logic about the attributes as I wrote in #13. I will now close the issue as the loading spinner is in the master.

Thanks again for this contribution!

Regards,

Guy
