### ISSUE TITLE
Need to propagate current searchQuery input in cancel-button-clicked-method

### ISSUE THREAD

**Issue by yonsonsal** [guylabs/ion-autocomplete#120]
Hi, I'm workgin on a suggestion for locations and direction and I need to get the user input before cancel button was clicked. I found easy to modify here to do that by adding a searchQuery property to the callback object.

     // cancel handler for the cancel button which clears the search input field model and hides the
                // search container and the ionic backdrop and calls the cancel button clicked callback
                ionAutocompleteController.cancelClick = function () {
                   var _searchQuery= ionAutocompleteController.searchQuery ;
                    ionAutocompleteController.searchQuery = undefined;
                    ionAutocompleteController.hideModal();
                    // call cancel button clicked callback
                    if (angular.isFunction(ionAutocompleteController.cancelButtonClickedMethod)) {
                        ionAutocompleteController.cancelButtonClickedMethod({
                            callback: {
                                selectedItems: ionAutocompleteController.selectedItems.slice(),
                                componentId: ionAutocompleteController.componentId,
                                searchQuery:_searchQuery
                            }
                        });
                    }
                };
          
What do you think?
Thanks!

**Comment by guylabs** [comment]
Hi,

could you maybe elaborate more on the use case? For what do you need the entered search query? You also have this information in the `items-method` already when the user writes something.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

due to inactivity I will close the issue. If you still have any issues or remarks please add a comment or reopen the issue.

Thanks and regards,

Guy
