### ISSUE TITLE
search results failing if result variable is uppercase and search input is lowercase

### ISSUE THREAD

**Issue by boyfunky** [guylabs/ion-autocomplete#121]
e.g. if i have my result array like this 

var homeworksingle = [
			{id: '1', name: 'Maths'}, 
			{id: '2', name: 'English'},
			{id: '3', name: 'Physics'}
		];

and when i try to search my list nd input 'm', it returns no result but when i input 'M' it returns data. 

How do i set it to also acknowledge or search when input is lowercase or uppercase.

**Comment by guylabs** [comment]
Hi Kingsley,

well you need to have the case insensitive logic in your `items-method`. The search input just forwards the searched string to the method and you need to return the proper values.

So you need to implement this by yourself. I hope it is clear and if not please reopen the issue again.

Thanks and regards,

Guy
