### ISSUE TITLE
Tag missing for 0.3.2

### ISSUE THREAD

**Issue by nuba** [guylabs/ion-autocomplete#122]
Hello there!

Release notes for 0.3.2 are out but tags go only as far as 0.3.1

Thanks in advance,

Nuba

~~~
$ bower install ion-autocomplete@0.3.2 --save
bower ion-autocomplete#~0.3.2       not-cached git://github.com/guylabs/ion-autocomplete.git#~0.3.2
bower ion-autocomplete#~0.3.2          resolve git://github.com/guylabs/ion-autocomplete.git#~0.3.2
bower ion-autocomplete#~0.3.2     ENORESTARGET No tag found that was able to satisfy ~0.3.2

Additional error details:
Available versions in git://github.com/guylabs/ion-autocomplete.git: 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.2, 0.0.1
~~~

**Comment by guylabs** [comment]
Hi Nuba,

`0.3.2` is not yet released and the release notes are already updated when an issue is fixed on the master. That is why there are already release notes despite the release is not out already. So you need to check the releases and then read the according release notes. You also see the latest version in the badges in the readme.

So can I close the issue as I think it should be clear why it is already there right?

Thanks and regards,

Guy

**Comment by nuba** [comment]
I see, thanks for the explanation! :P
