### ISSUE TITLE
selected items list empty when maxSelectedItems=1  

### ISSUE THREAD

**Issue by borys** [guylabs/ion-autocomplete#124]
Hello,
here is example, what I want to do (everything works): 
http://codepen.io/anon/pen/RrWJLb
(shortly: max-select-items=1 and set initial value with external-model)
I've tried to do the same in my project, but 'Selected Items:' list is empty (sorry, I couldn't replicate the problem in codepen, I guess it may be connected with using ionic menu )... 
Here are my conclusions after few hours of debugging:
- value of ng-model is correct
- selected item exist in DOM but is not visible
- condition "!viewModel.isArray(viewModel.selectedItems)" returns true (line 88 in master - ng-show condition in template)
- when max-selected-items=2, selected items list is viewed correctly

My solution: when I've changed 'ng-show' to 'ng-if' (line 88, master) everything works perfectly (as in example)

**Comment by guylabs** [comment]
Hi Przemysław,

thanks for reporting this issue. I just fixed this on the master. Could you maybe test it again and give me feedback such that I can close the issue?

Happy christmas and regards,

Guy

**Comment by borys** [comment]
Hi, 
I've just tested, and everything seems to work correctly, so You can close the issue.
Thanks a lot,

Przemek
