### ISSUE TITLE
Does ion-autocomplete works with textarea???? in ionic???

### ISSUE THREAD

**Issue by KusumaScriptbees** [guylabs/ion-autocomplete#129]
where in i have a requirement to use ion-autocomplete in textarea. Can you please let me know.

**Comment by guylabs** [comment]
Hi @KusumaScriptbees, 

sorry for my late reply but I was in vacations. There was already an issue about that and it is solved. Check out the solution here #68 and come back to me if it doesn't work. I will close the issue now as duplicate.

Thanks and regards,

Guy
