### ISSUE TITLE
autocomplete fails when a constant is inserted in the controller

### ISSUE THREAD

**Issue by srinigk** [guylabs/ion-autocomplete#131]
I am trying to use the ion-autocomplete and trying out the sample.  Everything works fine, except when I try to add a constant called 'airlines', the search items stop appearing. In fact the callback itself is not called. Please fix this. airlines is defined as a constant as shown below. 

.constant('airlines', [{
.....
}]);

Controller is

 .controller('IonAutocompleteController', ['airlines', function($scope, airlines) {

      $scope.airlines = airlines;
    $scope.model = "";
    $scope.clickedValueModel = "";
    $scope.removedValueModel = "";

    $scope.getAutoCompleteItems = function(query) {
        console.log(query);
      if (query) {
        return {
          items: [{
            id: "1",
            name: query + "1",
            recipeGroup: "view: " + query + "1"
          }, {
            recipeId: "2",
            recipeName: query + "2",
            recipeGroup: "view: " + query + "2"
          }, {
            recipeId: "3",
            recipeName: query + "3",
            recipeGroup: "view: " + query + "3"
          }]
        };
      }
      return {
        items: []
      };
    };

    $scope.itemsClicked = function(callback) {
      console.log(JSON.stringify(callback));
      $scope.clickedValueModel = callback;
    };
    $scope.itemsRemoved = function(callback) {
      console.log(JSON.stringify(callback));
      $scope.removedValueModel = callback;
    };
      
    }
  }])

**Comment by srinigk** [comment]
It is working now! I am not sure what I did wrong but, now in a different project it is working fine. So please treat the issue as closed.

**Comment by guylabs** [comment]
Hi @srinigk,

sorry for my late reply but I was in vacations. Good that you got it working!

Thanks and regards,

Guy
