### ISSUE TITLE
Issue with collection-repeat if multiple items are selected

### ISSUE THREAD

**Issue by samuelsmal** [guylabs/ion-autocomplete#136]
I am not sure, if the error is not directly with `collection-repeat` or with the directive itself.

However the list is wrongly redrawn after adding a few items. A few items from the top of the list populated with `viewModel.searchItems` are disappearing too soon. The problem does not occur when `ng-repeat` is used instead of `collection-repeat`.

See [plunker here](http://codepen.io/anon/pen/Nxgmqe?editors=101) for a test. Add five items and scroll a bit, the error should be visible clearly.

Note that the used directive is a [clone](https://github.com/samuelsmal/ion-autocomplete). I added some stuff and fixed an issue with the maximum allowed items to be selected.

For now I would advice to switch the `collection-repeat` directive for `ng-repeat`.

This issue is a duplicate of [issue 126](https://github.com/guylabs/ion-autocomplete/issues/126).

**Comment by guylabs** [comment]
Hi @samuelsmal,

thanks for pointing this out and for the fix. I will use the #126 issue as reference and will close this.

What exactly did you fix for the `max-selected-items` attribute? Maybe we can integrate it here with a PR.

Thanks and regards,

Guy
