### ISSUE TITLE
How to show thumbnail & name in populated list and as selected value

### ISSUE THREAD

**Issue by angel1st** [guylabs/ion-autocomplete#137]
Hi there, 
I this the control created by you is just great. I still need some time to figure out some aspects of it however and thus came to this question:
I have endpoint, which returns following data to the front end:

    [
        { id: '11111111111111',
          name: 'Name1',
          thumbnailUrl: 'http://mydomain.com/11111111111111/thumbnail'
        },
        { id: '2222222222222222222',
          name: 'Name2',
          thumbnailUrl: 'http://mydomain.com/2222222222222222222/thumbnail'
        },
        ......
        { id: '66666666666666666',
          name: 'Name2',
          thumbnailUrl: 'http://mydomain.com/66666666666666666/thumbnail'
        }
    ]

where each `thumbnailUrl` is a valid URL address.
I would like to have:

1. When autocomplete modal opens I would like to see a list of <thumbnail> <name> items
1. When item is selected, and autocomplete modal is closed, I would like to see selected item in the same format into the input control the one with `ion-autocomplete` attribute.

So how can I accomplish that?

**Comment by samuelsmal** [comment]
Not quite sure what you want. Can you post some sketches?

Anyway: To display the thumbnails in addition to the item's name you have to alter the template. Copy the given template (out of `src/ion-autocomplete.js`) and modify it accordingly. Set the `templateUrl` argument in your application's template.

To alter the display of the input element you can overwrite the used `ngModel.$render` method. You can have a look at my [fork](https://github.com/samuelsmal/ion-autocomplete/), where I added an argument where you pass a method. Although I think that you wont be able to do what you want with this method. I would draw the thumbnails outside of the input tag. Sadly I was not able to find a source to add HTML to the `ngModel.render` method.

**Comment by angel1st** [comment]
@samuelsmal - thanks for the feedback, I think the first part (regarding the list customization) is quite straightforward and I will follow it.
Regarding the display of the selected item (thumbnail & name) - I'm not sure I am following you for `$render` method - I don't think I can pass to this method html content, since what I need to have is something like: `<div><img ng-src="{{selectedItem.thumbnailUrl}}"> {{selectedItem.ame}}</div>` as the replacement of the `input` tag.

I'm curious if I can achieve what you mentioned by "I would draw the thumbnails outside of the input tag" - how can I do that?

Thanks again!

**Comment by samuelsmal** [comment]
Ok, I would clear the input tag, and overwrite the template:

```html
<div class="ion-autocomplete-container modal" ng-class="viewModel.randomCssClass">
  <div class="bar bar-header item-input-inset">
     <span class="iconWrapper">
        <i class="icon ion-ios-search placeholder-icon"></i>
      </span>
      <div class="searchWrapper">
        <div class="tag" ng-repeat="item in viewModel.selectedItems">
          <div><img ng-src="{{selectedItem.thumbnailUrl}}"><span ng-bind="item.name"></span></div>
        </div>
        <span class="inputWrapper">
          <input type="search" class="text-input form-control overTagSelector__search-input" ng-model="viewModel.searchQuery" ng-model-options="viewModel.ngModelOptions" placeholder="{{viewModel.placeholder}}"/>
        </span>
      </div>
   </div>
  </div>
  <ion-content class="has-header">
    <ion-item ng-if="!viewModel.searchQuery">
        <i class="icon ios-ios-information"></i>
        <span translate="emptySearch"></span>
    </ion-item>
    <ion-item ng-repeat="item in viewModel.searchItems" on-tap="viewModel.selectItem(item)" ng-if="viewModel.searchQuery">
    [...]
    </ion-item>
  </ion-content>
</div>
```

This should give you an idea. Bear in mind that I omitted some code.

The input tag is still populated with the model, so you have adapt this. I set this to `null`, as I add the tags myself.

**Comment by guylabs** [comment]
Hi @angel1st,

sorry for my late reply but I was in vacations. What is the status of the issue? Did you manage to get it to work?

@samuelsmal Thanks a lot for your help here!

Regards,

Guy

**Comment by angel1st** [comment]
@samuelsmal - thanks for the proposal I managed it the similar to the proposed fashion. @guylabs yes, it is solved, however with regards to the input tag, I would suggest you to make thumbnail / string option as part of the control, since I believe in most of the cases it would be very useful one.
