### ISSUE TITLE
template data

### ISSUE THREAD

**Issue by MazzMazz** [guylabs/ion-autocomplete#138]
Hey there,

I am using a custom template and want to add some custom data, but i am not able to make it work
The template itself is working but i am not able to access the template-data

```javascript
     $scope.templateDataRevier = {
            src:'revier',
            createNewMarker : function(){
                console.log("revier");
            }
        };
        // just to test if the templateData has to be named templateData
        $scope.templateData = {
            src:'templateData',
            createNewMarker : function(){
                console.log("templateData");
            }
        };
        $scope.templateDataPlace = {
            src:'place',
            createNewMarker : function(){
                console.log("place");
            }
        };
```
I tried the following
```javascript
<input ion-autocomplete 
....
template-data="templateDataRevier"
....
/>
// i also tested it with
template-data="templateData"
template-data="templateDataPlace"
```

And in the template i tested it like this (i used templateData and templateDataRevier because i don't know how i access the templateData in the template, so i tried both), but it doesn't get resolved
```
<button>{{templateData.src}} - {{templateDataRevier.src}}</button>
```

**Comment by samuelsmal** [comment]
Can you post more information? With filenames. A plunker would be great, too.

**Comment by MazzMazz** [comment]
It works if you put the viewModel before templateData.
```
<button>{{viewModel.templateData.src}}</button>
```
but executing a function still doesn't work
```javascript 
<button class=" button button-clear">

            <span class="ion ion-plus" ng-click="viewModel.templateData.createNewMarker()"></span>
        </button>
```

**Comment by MazzMazz** [comment]
Nevermind, the ng-click should be in the button tag ^^
then it works perfectly

**Comment by guylabs** [comment]
Hi @MazzMazz, 

sorry for my late reply but I was in vacations. Cool that you could fix the issue.

@samuelsmal Thanks for the help! Really appreciated!

Thanks and regards,

Guy
