### ISSUE TITLE
Model binding issue

### ISSUE THREAD

**Issue by 111crb111** [guylabs/ion-autocomplete#14]
Hi, after i clear model ther is still value in input.

Example:
```
<ion-autocomplete 
	ng-model="data.auto.registrationPlace" 
	items-method="registrationPlaceQuery(query)"
	placeholder=""
	cancel-label="back"
	item-view-value-key="nameFull" 
	name="registrationPlace"
	required/>
```
How can i clear the inpur field when programmatically clear model ?

**Comment by guylabs** [comment]
Hi,

yes I had a similar issue in the last days. I will have a look on it next week and hopefully fix it.

Thanks for pointing it out.

Regards,

Guy

**Comment by guylabs** [comment]
Hi,

I just checked in a fix such that if you set the model to `undefined` (or the model is already undefined) the view value is set to an empty string. I hope this fixes your issue. Could you please shortly test it and then tell me if it worked?

After that I am able to release a new version.

Thanks and regards,

Guy

**Comment by 111crb111** [comment]
It works :D
Thanks!
