### ISSUE TITLE
How to set max-selected-items dynamically

### ISSUE THREAD

**Issue by maurotrigo** [guylabs/ion-autocomplete#140]
Hello,

I'm trying to set max-selected-items with a scope variable **maxSelectedItems**, which in this case equals to **1**:

```
<input
	ion-autocomplete
	type="text"
	readonly="readonly"
	class="ion-autocomplete"
	autocomplete="off"
	name="{{ field.name }}"
	ng-model="bindModel[field.name]"
	ng-required="field.required"
	item-value-key="value"
	item-view-value-key="caption"
	items-method="selectQuery(query)"
	search-items="prepopulatedItems"
	model-to-item-method="modelToItemMethod(modelValue)"
	max-selected-items="{{ maxSelectedItems }}"
	placeholder="{{ field.placeholder || ('report_create-select_option' | translate) }}"
	cancel-label="{{ 'report_create-cancel' | translate }}"
	select-items-label="{{ field.placeholder || ('report_create-search' | translate) }}">
```

but this is what I get:

![image](https://cloud.githubusercontent.com/assets/2113593/12420438/f63764a8-be92-11e5-8ef0-4a718177aff0.png)

What am I doing wrong? Thanks in advance.

**Comment by samuelsmal** [comment]
Can confirm this. I find that `max-selected-items` somewhat weird anyway. I'll have a look in a few days. 

For now I would adjust the label function. Adjust the template and provide your own method. If you want, you can open an issue on my fork and I'll fix it, when I have time.

**Comment by guylabs** [comment]
Hi @maurotrigo,

As you see here I just get the `max-selected-items` by attribute and therefore you cannot bind it to a scope variable. I try to have a look how we can get rid of this property as it is not really needed.

Thanks and regards,

Guy

**Comment by maurotrigo** [comment]
Hi @guylabs and @samuelsmal,

Thanks a lot for your replies, I'll figure a way to make this work, I'll let you know if I find something useful for the project.

Best,

**Comment by BioPhoton** [comment]
Hi, @maurotrigo. 
Did you found a solution?
Would need this feature asap.

THX!

**Comment by guylabs** [comment]
Hi 

this has now been fixed on master and will be release with the `0.3.3` version. 

Now the `maxSelectedItems` can be changed dynamically. The only drawback is that the label will be overridden with the default when the value changes. To overcome this one needs to create its own template with the custom selected items label.

Sorry for the delay but better now than never ;).

Regards,

Guy
