### ISSUE TITLE
Not working with Ionic 1.2.*

### ISSUE THREAD

**Issue by HugoHeneault** [guylabs/ion-autocomplete#141]
Hi there,
Thanks for your nice directive! It was working perfectly... But not anymore

It seems to have some conflicts with latest ionic... (after updating from 1.1.* to 1.2.*)
Do you have some time to test ion-autocomplete against Ionic 1.2.*?

Thanks! :+1:

**Comment by samuelsmal** [comment]
Can you provide more information? What is not working? Console output?

**Comment by guylabs** [comment]
Hi @HugoHeneault,

sorry for my late reply but I was in vacations. Officially the directive is not tested with Ionic `1.2.*` so I first need to check it. What are the errors you get?

Thanks and regards,

Guy

**Comment by samuelsmal** [comment]
FYI: I am testing it with the `1.2.4` version of Ionic and didn't found any problems so far.

**Comment by guylabs** [comment]
Hi @HugoHeneault,

I just tested everything with the latest Ionic version `1.2.4` and all test pass and I also tested it manually. What is the exact error you get? I will upgrade the component to `1.2.4` in the `0.3.3` version but I first need to release the `0.3.2`.

Regards,

Guy

**Comment by rintuzi123** [comment]
Hi guy. I'm still facing problems in v1.2.4. When I click on the textbox it should open up the ion-autocomplete, but it's not happening. When I click on the textbox nothing happens, it acts like readonly. If I remove readonly,  it acts like a simple html textbox.

**Comment by HugoHeneault** [comment]
I don't have my code right now, but I'll come back to you as soon as I can. Thanks!

**Comment by guylabs** [comment]
I just upgraded to Ionic `1.2.4` and the build passes. Therefore I will close the issue and if you have any other problems with Ionic `1.2.4` please add them here and reopen the issue.

Thanks and regards,

Guy
