### ISSUE TITLE
Possible not use model?

### ISSUE THREAD

**Issue by zhouhao27** [guylabs/ion-autocomplete#144]
I mean if it's possible to show a inline list in form when the search input was clicked? Thanks

**Comment by guylabs** [comment]
Hi @zhouhao27, 

so when a user selects an item you want that it shows up in a list component? You can just create this component and then bind the model of the `ion-autocomplete` to it and then this should get updated accordingly.

Thanks and regards,

Guy

**Comment by zhouhao27** [comment]
ok. I see. I was just wondering if there is an option to do so. Thanks.

**Comment by guylabs** [comment]
No problem. Thanks for using it :smiley:.

Regards,

Guy
