### ISSUE TITLE
Greyed Out Page

### ISSUE THREAD

**Issue by jamesa8** [guylabs/ion-autocomplete#146]
Hi All, 

I retrieved the latest github instance of this library and copied the demo code into my ionic angular application. Unfortunately, however, when I attempt to test the search box the screen grays out and I am unable to click anything or type anything. I am running the application on a google chrome browser with developer tools. Is this a common issue when running on chrome?

Thanks,

Amber

**Comment by guylabs** [comment]
Hi Amber,

did you check your Ionic version here: https://github.com/guylabs/ion-autocomplete#ionic-compatibility Maybe you have an older version which is not compatible with the master. There is also an issue about the `1.2.4` version of Ionic and this should also work with the latest master. See here #141.

And if that is not the issue can you maybe test the following page and then move part by part to your project? https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.multiple-select.e2e.html

Thanks and regards,

Guy

**Comment by jamesa8** [comment]
Hey Guy, 

You were very correct. Thank you for your help! 

Amber

**Comment by guylabs** [comment]
Hi Amber,

no problem. Good that it now works :smiley: and thanks for using it!

Regards,

Guy
