### ISSUE TITLE
Prefill data on load

### ISSUE THREAD

**Issue by o-mar** [guylabs/ion-autocomplete#147]
Hello,
I'm trying to find how to prefill some data on load so it will be checked in search and be presented in input.
Thanks in advance!

**Comment by guylabs** [comment]
Hi Oleg,

please have a look at the documentation here https://github.com/guylabs/ion-autocomplete#external-model. There everything is written how to pre populate the model. You also need to implement the proper https://github.com/guylabs/ion-autocomplete#the-model-to-item-method method.

Thanks and regards,

Guy

**Comment by o-mar** [comment]
Hi,
I'm getting "getModelItem is not defined" - http://codepen.io/anon/pen/bEJrXq
Thanks!

**Comment by guylabs** [comment]
Hi Oleg,

this method you need to implement by your own. In the commit I did I just updated the documentation about it. Please read it again and then implement the logic and then it should work.

Thanks and regards,

Guy

**Comment by o-mar** [comment]
Thank you for explanation!

**Comment by guylabs** [comment]
No problem. Can you then please close the issue when you managed to get it to work?

Thanks and regards,

Guy

**Comment by o-mar** [comment]
sorry, as I understand you right it will prefill data here http://prntscr.com/a4s0zv but not in autocomplete input(I need both).
Thanks a lot!

**Comment by guylabs** [comment]
well when you set the external model properly then both will be pre populated with the data. Check the sample here as there you see that both are pre populated: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.prepopulated.e2e.html

**Comment by o-mar** [comment]
Many thanks for this!!! tested here http://codepen.io/anon/pen/rxbbqJ?editors=1010 and all is ok for me!
Thanks again!

**Comment by guylabs** [comment]
Ok great that you got it to work :smiley: and thanks for using it.

Regards,

Guy

**Comment by o-mar** [comment]
giving you a star. Thanks!
