### ISSUE TITLE
Item width not auto on window phone

### ISSUE THREAD

**Issue by huskywhale** [guylabs/ion-autocomplete#148]
![image](https://cloud.githubusercontent.com/assets/9066230/13125275/fbd8bec2-d592-11e5-8a43-06bc61ddeed7.png)

Any help ?

**Comment by guylabs** [comment]
Hi @huskywhale,

could you please give me more information about which Ionic/`ion-autocomplete` version you use, do you use a custom template? Can you please provide the code how you configure the directive?

I am not able to test it on a Windows phone but maybe there is an a configuration issue. For me it looks like you use a custom template/css as the color of your shown items differ with the standard one.  Did you test this template on your Windows phone: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.multiple-select.e2e.html ? Does that work as this is standard.

Thanks and regards,

Guy

**Comment by huskywhale** [comment]
I am using ionic 1.2.4 and the latest version of ion-autocomplete.

Realised the problem was that despite me telling VS to use the newest version of Ion-Autocomplete. It was using an older version (0.1). 

Thanks for the quick reply
