### ISSUE TITLE
template-url/template-data question

### ISSUE THREAD

**Issue by germgerm** [guylabs/ion-autocomplete#152]
I am using a custom template to add a "NEW" button
The button display fine but I can't determine how to handle the click event
I tried a newClicked function on the templateData and set the button's ng-click="templateData.newClicked()" but it never fires
I also added a simple text field to the template data and can't even display that so I am thinking that maybe the issue is that I am adding the template data to the wrong scope

so 2 questions 
Is there a working example of using a custom template with template data ?
Is this the proper approach for adding custom element even handlers ? If not how should it be done and is there an example.

Thanks
Gerry

**Comment by guylabs** [comment]
Hi @germgerm,

do you set an object as `templateData` attribute? (As it is described here: https://github.com/guylabs/ion-autocomplete#template-data)

And no there is no example for that just a unit test here: https://github.com/guylabs/ion-autocomplete/blob/master/test/ion-autocomplete.single-select.spec.js#L330

There are surely other ways of adding event handlers, but the `template-data` is the only way of passing data from the outer scope to the custom template scope.

Could you maybe create a codepen with a sample such that I can check it there?

Thanks and regards,

Guy

**Comment by germgerm** [comment]
thanks

I ended up just wiring up the event manually - works well - the event was the only reason for using the template-data so will revisit if required in the future

I also ran into a performance issue ( 700+ items ) - changing all binding to one way seemed to help a small bit but the !!! huge !!! improvement came by changing ng-repeat to collection-repeat displaying/filtering the list went from many seconds to almost instantaneous - I noticed that you switched from collection to ng recently but I don't see any mention of why - for me ng-repeat performance is a show stopper and so far collection-repeat hasn't caused any issues.

Gerry

**Comment by samuelsmal** [comment]
>  I noticed that you switched from collection to ng recently but I don't see any mention of why - for me ng-repeat performance is a show stopper and so far collection-repeat hasn't caused any issues.

As this was my suggestion:

`collection-repeat` has some issues with redrawing. Not sure what exactly is causing the issue. `collection-repeat` only draws the items that should be seen, so this improves the rendering.

Have a look at [issue #136](https://github.com/guylabs/ion-autocomplete/issues/136) and see if you can reproduce the issue.

**Comment by germgerm** [comment]
Not seeing the problem however I am not using multi select - so maybe that's why ?
Or maybe I am just missing the problem because I also don't see it in the codepen example mentioned in #136

**Comment by samuelsmal** [comment]
Ah, sorry. I applied my fix on that. Can you try again and alter the version of `ion-autocomplete`?

**Comment by germgerm** [comment]
sorry - new to this - how do I alter the version  ?

**Comment by guylabs** [comment]
Hi @germgerm,

I think @samuelsmal means to use the version of this repository here. So please replace the following line in the plunkr:

```javascript
<script src="https://rawgit.com/samuelsmal/ion-autocomplete/master/src/ion-autocomplete.js"></script>
```
with the following line:

```javascript
<script src="https://rawgit.com/guylabs/ion-autocomplete/master/src/ion-autocomplete.js"></script>
```
and then try again.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @germgerm,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
