### ISSUE TITLE
cannot scroll the autocomplete list

### ISSUE THREAD

**Issue by ghost** [guylabs/ion-autocomplete#153]

**Comment by guylabs** [comment]
Hi @OutfitPic,

could you please add more information about your issue like Ionic version, `ion-autocomplete` version etc. The best would be a codepen sample where the issue is reproducible.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
