### ISSUE TITLE
Backdrop of an Ionic popup is not shown

### ISSUE THREAD

**Issue by sebrojas14** [guylabs/ion-autocomplete#155]
The ion-autocomplete modal doesn't behaves like a normal modal and than gives me problems. For example, I can´t show a Ionic confirmation modal with the ion-autocomplete showing (appears behind the ion-autocomplete)

**Comment by guylabs** [comment]
Hi @sebrojas14, 

could you maybe provide a codepen where I can reproduce this issue? Then I can have a look at it.

Thanks and regards,

Guy

**Comment by sebrojas14** [comment]
As soon as possible

**Comment by sebrojas14** [comment]
How can I use ion-autocomplete on codepen? there is a CDN?

**Comment by sebrojas14** [comment]
Ready: http://codepen.io/anon/pen/bprxwd

**Comment by guylabs** [comment]
Hi @sebrojas14, 

I just checked the codepen and you solution with chaning the `z-index` is the only way to solve that. By default Ionic has the following `z-indexes`: https://github.com/driftyco/ionic/blob/v1.1.1/scss/_variables.scss#L720 and therefore we need to set the `z-index` to 11 in the `ion-autocomplete.css` and this solves the issue. Would that be a solution for you? If yes I will change that and commit it to master.

Thanks for finding this issue!

Regards,

Guy

**Comment by sebrojas14** [comment]
I don't know, because as I told you, with that z-index appears the popup but not the backdrop, so is not a complete solution, it has to be anotehr way.

**Comment by guylabs** [comment]
I see the backdrop within the browser (Chrome). Can you maybe use the latest master with the changed CSS with the `z-index` set to `11`? I also use the latest official Ionic version `1.2.4`. What version do you use?

**Comment by sebrojas14** [comment]
I use Ionic 1.2.4. What do you mean with "I see the backdrop within the browser (Chrome)" do you see it or do you see it in the page code?

**Comment by guylabs** [comment]
I see the backdrop with the adapted (added the `ionicPopup` call) test html I use for the e2e tests: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.multiple-select.e2e.html :
![screen shot 2016-03-31 at 19 18 01](https://cloud.githubusercontent.com/assets/1892848/14184460/8efebedc-f775-11e5-9e09-15c345d4bc25.png)
And I see it in your codepen:
![screen shot 2016-03-31 at 19 19 33](https://cloud.githubusercontent.com/assets/1892848/14184459/8efe6e50-f775-11e5-87bc-9e8ea3324214.png)

**Comment by sebrojas14** [comment]
Yes but the backdrop should be over the ion-autocomplete, or not?

**Comment by guylabs** [comment]
Sorry for the late reply. I just checked again and now I get your point with the backdrop ;). Well in this case there is no other way than doing it this way (setting the `z-index` to `11`). Maybe you could also add a drop shadow to the dialog box with CSS such that this gets a little bit disconnected from the autocomplete modal. See https://forum.ionicframework.com/t/how-to-style-ionicpopup-alert/3228/5 for an example.

**Comment by guylabs** [comment]
Hi,

I will close the issue as wont fix. Please reopen it if there is another option on how to fix this.

Thanks and regards,

Guy
