### ISSUE TITLE
Setting more than 1 items-method-value-key?

### ISSUE THREAD

**Issue by lync0056** [guylabs/ion-autocomplete#156]
Does anybody know how I might do this?

My attempts not bearing any fruit.

HTML
items-method-value-key="items, address, title" ??

Javascript
var returnValue = { items: []; address[]; title[]; };

returnValue.items.push(results);
returnValue.address.push(results);
returnValue.title.push(results);

Cheers

Cameron

**Comment by guylabs** [comment]
Hi Cameron,

this is not possible. You can aggregate these values into one string, add it to the result object and then return and reference it in the `items-method-value-key`.

I hope this helps.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @lync0056,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
