### ISSUE TITLE
set default selected value

### ISSUE THREAD

**Issue by boyfunky** [guylabs/ion-autocomplete#157]
So i have a list of items and while it works fine. I want it to be able to upon load, set the default selected object of the results. e.g. i have a list of cars
`[
    {
        "id": "1",
        "name": "Item 1",
    },
   {
        "id": "2",
        "name": "Item 2",
    }
]`
  i want once the ionautocomplete load, that it sets the selected item to item 2. 

How do i do that with ion-autocomplete?

**Comment by guylabs** [comment]
Hi @boyfunky,

please have a look at the https://github.com/guylabs/ion-autocomplete#external-model documentation. You can also have a look at this https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.prepopulated.e2e.html example as this is used in the tests.

Please come back to me if it worked such that I can close the issue.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @boyfunky ,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
