### ISSUE TITLE
Dealing with empty results

### ISSUE THREAD

**Issue by AugmentBLU** [guylabs/ion-autocomplete#159]
Hello,

I was wondering how we can deal with no results being found after a search has completed. Basically we're using a get request to build the items list but wondered if there was no results, how do we disable the selection event?

**Basic controller function**

`scope.getAddresses = function (query) {
  if (query.length < 3)
                    return;requestUrl = $http.get('myurl.json', {
                    params: {
                        autocomplete: true,
                        location: query
                    }
                });
}`

**Basic no results response**
`array('name'=>'no results found')`

When the no results response appears, only one item is created in the list showing `no results found` but it's still selectable - which we hoped to disable.

![ion-autocomplete](https://cloud.githubusercontent.com/assets/442602/14602681/27b845d2-0561-11e6-8aec-eb75fcdfb479.png)

Thanks,
Ross

**Comment by guylabs** [comment]
Hi @AugmentBLU,

maybe you can open up a Ionic dialog in the `items-method` when nothing is returned from the back end.
Then you are in control of this and not the directive. Would that be a solution for you?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @AugmentBLU,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
