### ISSUE TITLE
Demo for using google api for searching addresses

### ISSUE THREAD

**Issue by BioPhoton** [guylabs/ion-autocomplete#160]
Hi guylabs,

first of all thanks for the great work and also thanks to danny for the initial work!!

I was not able to find examples for working with google api. Did i overlooked this point in the docs?

thx!

**Comment by BioPhoton** [comment]
Hi, it was an easy task to implement. Just used the geocode method for the items-method.

**Comment by guylabs** [comment]
Hi @BioPhoton,

cool that you could easily implement it yourself. Could you maybe add the example as a codepen here such that I could add it to the documentation with a reference to you?

Thanks and regards,

Guy

**Comment by BioPhoton** [comment]
Hi, i created a pull request with the implementation. 

happy to contribute...

**Comment by guylabs** [comment]
Hi @BioPhoton,

thanks a lot for the contribution. I already merged it :)

Regards,

Guy

**Comment by BioPhoton** [comment]
wellcome!
