### ISSUE TITLE
ng-if messes up the item-view-value-key functionality

### ISSUE THREAD

**Issue by BioPhoton** [guylabs/ion-autocomplete#161]
If i query and select items (in my case google addresses) and use the item-view-value-key to display the formatted_address as value. every thing works fine.

If i then hide and show the input over the ng-if attribute the inputs model value changes to the whole google geocode obj and not displaying just the formatted_adress prop as defined over the item-view-value-key attribute.

If i change to ng-show everything works fine

**Comment by guylabs** [comment]
Hi @BioPhoton,

could you maybe create a codepen showing the issue such that this is reproducible? So you hide the input where you defined the directive right?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @BioPhoton,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
