### ISSUE TITLE
Placeholder text is the only thing visible when you first view the page with autocomplete

### ISSUE THREAD

**Issue by kweiganddmp** [guylabs/ion-autocomplete#162]
Thanks for your module. I noticed that when I first open a view that only has the autocomplete directive nested inside the ion-view and ion-content tags that the only thing that is visible is the placeholder text in the content area. Once the placeholder text is clicked, The input field opens in the header. After a search and selection of an item. The selected item appears as placeholder text in the content area--once you click the placeholder text, The selected item opens in the ion-item view with the icons to left and right. 

Is the directive designed to work this way ?(appearance of placeholder text only)
If so, is it possible to change? 
I would like to use a button instead of placeholder text on initial page load.

![image](https://cloud.githubusercontent.com/assets/9536622/14722057/4d1b17a8-07cf-11e6-9306-ad7d8b80209e.png)

^initial pageload 

![image](https://cloud.githubusercontent.com/assets/9536622/14722068/5a40ad4e-07cf-11e6-9a40-8259fcf786ca.png)

^search appears after placeholder text is clicked

![image](https://cloud.githubusercontent.com/assets/9536622/14722085/6f11aeb2-07cf-11e6-9be8-608284179c94.png)

Placeholder text is back. A click will allow you to select and see the ion-item view

![image](https://cloud.githubusercontent.com/assets/9536622/14722097/8014c9ec-07cf-11e6-92cc-91dbb0c3139c.png)
^ After Click

I am using a custom template, however this behavior was the same before customization. 

Again, is this normal and is there a way to modify it? 
I would like to use a search button instead of placeholder text to have the search input appear initially.
I would also like to skip the visible placeholder text after the selection of an item.

Thank you in advance for your help and thank you for taking the time to create this fine directive!

**Comment by guylabs** [comment]
Hi @kweiganddmp,

sorry for my late reply, but currently I have nearly no time for the support here and I try my best ;). Well it looks like you do not use any label for the input and therefore you just see the placeholder. See this example here for a running example with a label: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.multiple-select.e2e.html#L51

If you want to click on a seperate button to select the items then you can have a look at the `manage-externally` attribute which is documented here: https://github.com/guylabs/ion-autocomplete#manage-externally. With this you are able to create such a button which then opens the search dialog.

I hope I could help you out.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @kweiganddmp,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
