### ISSUE TITLE
Loading Icon Not Hidden Upon Search Fail

### ISSUE THREAD

**Issue by edmondchui** [guylabs/ion-autocomplete#163]
When a search fails, the loading icon is not hidden.

The loading icon is only hidden in the success case:

https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L269-L270

The code to hide the loading icon should be refactored to a finally block for the promise.

**Comment by guylabs** [comment]
Fixed by #164. Thanks @edmondchui for the contribution!

Regards,

Guy
