### ISSUE TITLE
Prepopulate many items

### ISSUE THREAD

**Issue by martinsdesa** [guylabs/ion-autocomplete#167]
Hi people. I tried prepopulate many items but without success.

`$scope.contacts = $scope.mensagem.para;` // this is my object with many contacts to send 
message.
 The object is like this: 
`[{"id": "1", "usuario": "usuario1",  "chave": "chave1" }, {"id": "1", "usuario": "usuario1",  "chave": "chave1" }, {"id": "1", "usuario": "usuario1",  "chave": "chave1" }]`

If i return a single value works fine and one selected item will be selected.
`$scope.modelToItemMethod = function (modelValue) {  
  return "id": "1", "usuario": "usuario1",  "chave": "chave1" }; Example. I Know that this function iterate values.
}`
I need prepopulate all items received in $scope.contacts;

**Comment by guylabs** [comment]
Hi @martinsdesa,

can you maybe create a codepen and show me the issue there? You can also have a look at the following example here where items are prepopulated:

https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.prepopulated.e2e.html

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @martinsdesa,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
