### ISSUE TITLE
render the view value of the model is not working

### ISSUE THREAD

**Issue by alexcunha** [guylabs/ion-autocomplete#17]
Render the view value of the model is not working, this is always rendering an object list, that's because the code inside of ngModel.$render is not being executed. 

I just added this line below and solved my problem:
        return {
        	priority: 1,

**Comment by guylabs** [comment]
Hi,

can you please elaborate more on this issue? Can you maybe show me your code and the model which you set and the configuration of the `ion-autocomplete`?

And what about your line which solved the problem? I think this is not complete.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi, 

any news here? I'll close the issue due to inactivity after 10 days of my last response. You can always reopen it if you want to.

Thanks and regards.
