### ISSUE TITLE
Tree structure

### ISSUE THREAD

**Issue by amilino** [guylabs/ion-autocomplete#171]
Is it possible to display items as a tree structure?

This is exactly what I need:
https://github.com/fer/ion-tree-list

**Comment by guylabs** [comment]
Hi @amilino,

this is not planned but a PR/branch with a prototype where you could enable the tree view in the selection list would be nice :). But how to define the data structure to show the tree is not that easy.

Thanks for the idea and regards,

Guy

**Comment by amilino** [comment]
I am working on it and will come back with results.

**Comment by guylabs** [comment]
Hi

any news on this? I will close the issue now due to inactivity. If you still have some comments or other inquiries, then please comment and reopen the issue.

Thanks and regards,

Guy
