### ISSUE TITLE
Optional Select/-ed items label

### ISSUE THREAD

**Issue by rodrigobnn** [guylabs/ion-autocomplete#172]
I needed to create an autocomplete without both Select and Selected items label, but there is no option to take out the message and ion-item from them. would be nice to have this option in a future version.

Thanks for the ion-autocomplete! Very nice!

**Comment by guylabs** [comment]
Hi @rodrigobnn,

thanks for taking that up. I will try to add it to the `0.3.3` release such that you are able to set empty values.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @rodrigobnn 

the easiest way is to create a own custom template where you do not have these two `ion-item` defined. You can have a look at this here: https://github.com/guylabs/ion-autocomplete#template-url

Therefore I will close this issue as this is the way to go. Adding a custom functionality just blows up the codebase.

Thanks and regards,

Guy
