### ISSUE TITLE
Display more than one item-view-value-key

### ISSUE THREAD

**Issue by irfanr** [guylabs/ion-autocomplete#174]
Hi,

Can I display more than one value as in "item-view-value-key"? In example, I want to display 'code' and 'description', I've tried to use it like this:

`          <input ion-autocomplete type="text" rcounteadonly="readonly" class="ion-autocomplete" autocomplete="off" max-selected-items="1" ng-model="expense.account" items-method="callbackMethod(query)" item-view-value-key="[no,desc]"/>`

It displayed the values, but it also displayed the unwanted square brackets and double quotes.

![screenshot from 2016-05-09 22 16 33](https://cloud.githubusercontent.com/assets/310289/15117860/bfb1f684-1633-11e6-9e96-3f001d3135e8.png)

Should be a better method for doing this? Big thanks for the helps :)

**Comment by guylabs** [comment]
Hi @irfanr,

please have a look at this part of the documentation: https://github.com/guylabs/ion-autocomplete#using-expressions-in-value-keys

As you see all value keys are parsed with the Angular `$parse` service. This means that you could set the `item-view-value-key` to something like `no: desc` and it should show `521: Call`. Could you please try it and come back to me?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @irfanr,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy

**Comment by brunodeprez** [comment]
Hi,

would it be possible to re-open this issue? I have the same needs as irfanr, and I tried to use `no: desc` style string and it failed. The possibility to style the output would be a big plus, as I need `(code) desc`

Thanks

**Comment by guylabs** [comment]
Hi @brunodeprez,

could you maybe show me a failing example in a codepen such that I see what you exactly need?

Thanks and regards,

Guy
