### ISSUE TITLE
template-url dynamic loading

### ISSUE THREAD

**Issue by amilino** [guylabs/ion-autocomplete#175]
How to bind template-url dynamically with expression. I tried ng-attr-template-url="{{...}}" with no luck. Any suggestion?

Many thanks in advance.

**Comment by guylabs** [comment]
Hi @amilino,

currently the `templateUrl` is not bound to the controller and therefore you cannot use it dynamically. See https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L41. 

What is the use case behind this that you need to change the `templateUrl` dynamically?

Thanks and regards,

Guy

**Comment by amilino** [comment]
Tnx for a quick reply.

Basically I want to build template with this tree structure directive:
https://github.com/fer/ion-tree-list

So based on expression logic switch template dynamically, from normal to tree structure.

What do you think?

**Comment by amilino** [comment]
I am currently using ngif direcitve, but that doesn't look nice.

**Comment by guylabs** [comment]
Hi @amilino,

what kind of expression logic do you mean? On what should the expression be based on?

Thanks and regards,

Guy

**Comment by amilino** [comment]
Here goes example:
` ng-attr-template-url="{{'1' == '1' ? 'common/autocomplete_tree_template.html' : 'common/autocomplete_template.html'}}"`

**Comment by guylabs** [comment]
Hi @amilino,

ok nice! So then you do not need any changes on the directive as you define it in the configuration with the basic Angular expressions.

Can we then close this issue?

Thanks and regards,

Guy

**Comment by amilino** [comment]
Hi @guylabs,

this expression doesn't work. I receive error:
ionic.bundle.js:25642 Error: [$compile:tpload] Failed to load template: {{'1' == '1' ? 'common/autocomplete_tree_template.html' : 'common/autocomplete_template.html'}} (HTTP status: 404 Not Found)...

so currently I copy/pasted control and added this:
`ng-if="group.CRIT_TYPE == 'LIST'"`

for one and:
`ng-if="group.CRIT_TYPE == 'TREE'"`

for second control.

**Comment by guylabs** [comment]
Hi @amilino,

sorry I misunderstood you and I will fix this issue as soon as possible.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @amilino,

could you please test this on the master and give me feedback? I just fixed it.

Thanks and regards,

Guy

**Comment by amilino** [comment]
Hi @guylabs,

I just used https://github.com/guylabs/ion-autocomplete.git#master as a bower dependency and same thing.

[$compile:tpload] Failed to load template: common/autocomplete_tree_template (HTTP status: 404 Not Found)

**Comment by guylabs** [comment]
HI @amilino,

yes but the exception is another one when you compare with the previous exception you had. The expression is now properly resolved, but you have issues with the template loading itself.

Please check that the template itself is working properly.

So can I then close this issue?

Thanks and regards,

Guy

**Comment by amilino** [comment]
Hi @guylabs,

template is working correctly and it does exist.

Checked already.

Thank you for fast reply.

**Comment by guylabs** [comment]
Hi @amilino,

well can you maybe debug it and add a breakpoint here https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L109 and then check what the value is of the `templateUrl`? For me it looks like the `.html` suffix is missing from the template url itself.

Thanks and regards,

Guy

**Comment by amilino** [comment]
Hi @guylabs,

hmm. This is strange. URL is correct.

`ionAutocompleteController.templateUrl = "common/autocomplete_template.html"`

Regards,
Alan

**Comment by amilino** [comment]
Sorry it was the second url which missed ".html" at the end.

Thank you very much, and sorry for my mistake.

All best!

**Comment by guylabs** [comment]
Hi @amilino,

ok cool that it works now! 😃 

Thanks and regards,

Guy
