### ISSUE TITLE
select from $http list

### ISSUE THREAD

**Issue by tinocosta84** [guylabs/ion-autocomplete#176]
how can I select from an API say parse.com with $http

**Comment by guylabs** [comment]
Hi @tinocosta84,

you need to configure the directive with the proper `items-method` (https://github.com/guylabs/ion-autocomplete#the-items-method) and then depending on your response JSON object the needed values like `items-method-value-key`, `item-value-key` and `item-view-value-key`. You can also have a look at the running codepen on how to configure it: http://codepen.io/guylabs/pen/GJmwMw

I hope this helps.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @tinocosta84,

I will close the issue due to inactivity. Please reopen it if there is still an issue.

Thanks and regards,

Guy
