### ISSUE TITLE
search text disapear in multiselect mode

### ISSUE THREAD

**Issue by amilino** [guylabs/ion-autocomplete#178]
Why do you clear search text after select item event? it's ok when you are not in multiselect mode, because window is closed after selection. But if you want to select multiple items for me it doesn't make sense to clear input field, because you are still at the same window...

Regards,
Alan

**Comment by guylabs** [comment]
Hi @amilino,

well this depends on the items you want to select. If you have items which start with the same string then it would be feasible not to clear the search input, but when you have different values then you always need to delete the search text in the input.

Also the other autocomplete implementations like [Select2](https://select2.github.io) do it this way that they clear the searched text when having a multiple select.

As I do not have enough time now to add this and if you really need this functionality then you could create a pull request with a flag with which you are able to change this functionality and then I can merge this to the master.

Thanks and regards,

Guy

**Comment by amilino** [comment]
Hi @guylabs,

just added pull request with possibility to disable clearing of input field after selecting item(s). Please merge it with the master branch.


Thank you and regards,
Alan

**Comment by guylabs** [comment]
#186 has been merged to master so I will close this issue.

Thanks for the contribution and regards,

Guy
