### ISSUE TITLE
How can I call the auto complete form in the ng-click

### ISSUE THREAD

**Issue by jokerxvier** [guylabs/ion-autocomplete#18]
hi,

I have a problem with calling the auto complete page or form on ng-click. how can i call the auto complete in ng-click? any solution here?

**Comment by guylabs** [comment]
Hi Jason,

so you want to open the autocomplete modal within your own `ng-click` right? This is currently not possible. Why do you need this behavior? Could you elaborate more on this? Don't you need the input field for the `ion-autocomplete` on which the user should click?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Jason, 

any news here? I'll close the issue due to inactivity after 10 days of my last response. You can always reopen it if you want to.

Thanks and regards.

**Comment by jokerxvier** [comment]
hi this is done already. thanks

**Comment by Heechan79** [comment]
@jokerxvier have you found a solution for the ng-click? I want to implement this as well..

**Comment by jawgardner** [comment]
Me too....

**Comment by guylabs** [comment]
@Heechan79 @jawgardner could you two maybe elaborate more on the use case of calling the search popup from another `ng-click`?
