### ISSUE TITLE
done button clicked method

### ISSUE THREAD

**Issue by sayginburak** [guylabs/ion-autocomplete#180]
Hi, feature set says there is a feature to configure done button clicked but documentation doesn't mention about it? Documentation is missing or feature set is wrong?

**Comment by guylabs** [comment]
Hi @sayginburak,

thanks for telling me this. I just updated the documentation and you can find it here: https://github.com/guylabs/ion-autocomplete#the-cancel-button-clicked-method-same-as-done-button

Thanks and regards,

Guy
