### ISSUE TITLE
item-value-key and item-view-value-key dynamic loading

### ISSUE THREAD

**Issue by brunodeprez** [guylabs/ion-autocomplete#181]
Hi,

Similar to #175, would it possible to bind properties item-value-key and item-view-value-key to be used like:

`item-value-key='{{key}}' item-view-value-key='{{value}}'`

Use case: I use your directive for different objects for which the key and the value properties come from a function for re-usability

Thanks

**Comment by guylabs** [comment]
HI @brunodeprez,

I just fixed this on the master. Could you shortly try it and give me feedback?

Thanks and regards,

Guy

**Comment by brunodeprez** [comment]
Hi @guylabs,

I just tested it and it works perfectly, thank you! 
Could you make it part of 0.3.3 on bower when you decide to push it?

Cheers
Bruno

**Comment by guylabs** [comment]
HI @brunodeprez,

yes it is already on master and it will be released with `0.3.3`.

Thanks and regards,

Guy
