### ISSUE TITLE
Required attribute doesn't work as expected

### ISSUE THREAD

**Issue by sebrojas14** [guylabs/ion-autocomplete#184]
If I put the required attribute, and a validate de form, it works, but if I select a value, and then delete thee selection, it doesn't works

**Comment by guylabs** [comment]
Hi @sebrojas14,

could you maybe prepare a codepen example of this issue such that I can reproduce it easily? There was an other issues dealing with this: #5. Therefore an example on how you do the validation would be useful to have a look at it.

Thanks and regards,

Guy

**Comment by sebrojas14** [comment]
A soon as I have a free minute

**Comment by guylabs** [comment]
Hi @sebrojas14,

are you able to provide a codepen? If not I will close the issue and you can reopen it when you got some time again. Is that ok for you?

Thanks and regards,

Guy
