### ISSUE TITLE
HTTP post on items-method. How to make it work.

### ISSUE THREAD

**Issue by besingamkb** [guylabs/ion-autocomplete#188]
Hi . I am trying to have an http post call on a server on every query. but I can't make it work. the autocomplete display nothing. here what I do. 

```javascript
$scope.contactQuery = function(query, isInitializing) {
    return {
        contacts: $http.post(Api.url+ '/search', { search: query } ).success(function() {
            return data.data;
        })
    }
}
```

here some sample result
```json
{
    "data": [
        {
            "id": 1231231,
            "name": "Jon Doe",
            "number": "+12345678910",
            "type": "user"
        }
    ]
}
```

**Comment by wryel** [comment]
Hi, try this for debug:
 
```
$scope.contactQuery = function(query, isInitializing) { 
    return $http.post(Api.url+ '/search', { search: query } ).then(function(response) {
        return response.data.data; // response.data is the return json, response.data.data is array
    }, function(error) {
        alert(error);
    });
}
```

**Comment by besingamkb** [comment]
i got this error when I use the code above. @wryel 

```code
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in viewModel.searchItems, Duplicate key: undefined:undefined, Duplicate value: undefined
```

**Comment by guylabs** [comment]
Hi @besingamkb,

sorry for my delay but I was on a longer trip and now I am working partially.

Can you maybe provide the `ion-autocomplete` directive configuration? You need to return a promise as @wryel showed it. And do you have a own template defined? As the error should not show up with the duplicate key as the default template uses a `track by $index` clause: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L98

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi

could you maybe answer the questions. If not I will close the issue and you can reopen it whenever you have time again.

Thanks and regards,

Guy
