### ISSUE TITLE
Support Ionic 1.3

### ISSUE THREAD

**Issue by engkordi** [guylabs/ion-autocomplete#189]
Did you have plan to support ionic 1.3 ?

**Comment by metalaureate** [comment]
As far as I can tell (not an expert) it works for Ionic 1.3 except for `isInitializing` which is never called.

**Comment by engkordi** [comment]
I tried this but without any hope, the issue with "items-method" directive.

**Comment by guylabs** [comment]
Hi

sorry for my delay but I was on a longer trip and now I am working partially.

Yes I will try to support it in version `0.4.0`. I will first release the `0.3.3` and then go ahead with that one.

Could @metalaureate  and @engkordi maybe provide more information about the issues they had and maybe how they worked around it/fixed it? 

Thanks and regards,

Guy

**Comment by djehring** [comment]
I have encountered another issue with using 1.3. The searchInput is rendered behind the $ionicBackdrop so is unresponsive. Adding z-index:12 to the template style fixes the issue

**Comment by guylabs** [comment]
@djehring Thanks for pointing this out! I will try to work on it asap, but currently I am still abroad and do not know when I got the time again.

**Comment by guylabs** [comment]
Hi

I finally got some time and this is now fixed on master and will be released in `1.4.0`. In the latest `1.3.2` version I did not encounter these issues. 

Could you maybe test it if you have the time. I will then release `1.4.0` anyway as there are other issues pending.

Regards,

Guy
