### ISSUE TITLE
Floating ion-label within RTL direction element

### ISSUE THREAD

**Issue by devoraf** [guylabs/ion-autocomplete#192]
hi,
when using floating ion-label with RTL direction, the floating label does not being aligned to the right, but somewhere in the middle, when typing text in the input field.
is there any solution for it?
see code below.

thanks,
Devora.

`<ion-list dir="rtl">
<ion-item>
    <ion-label floating >{{ usrTitle }}</ion-label>
    <ion-input type="text" [(ngModel)]="usrValue"></ion-input>
  </ion-item>
  <ion-item>
    <ion-label floating >{{ pswTitle }}</ion-label>
    <ion-input type="password" [(ngModel)]="pswValue"></ion-input>
  </ion-item>
</ion-list>`

**Comment by guylabs** [comment]
Hi @devoraf,

sorry for my delay but I was on a longer trip and now I am working partially.

So does that only happen with the `ion-autocomplete` directive? As the code snippet you sent me is just default Ionic code. If that is the case, then please create an issue in their github project.

If not, could you maybe provide a codepen such that I can see it easily and am able to reproduce it? Please also check #77 as there were also problems with the floating labels.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi

could you maybe answer the questions. If not I will close the issue and you can reopen it whenever you have time again.

Thanks and regards,

Guy

**Comment by joesleiman** [comment]
```
<ion-item>
        <ion-label floating>{{'LOGIN.USERNAME' | translate}}</ion-label>
        <ion-input type="email" formControlName="email"></ion-input>
 </ion-item>
```
i have same issue

**Comment by guylabs** [comment]
Hi @joesleiman 

as stated before if it is only in pure Ionic, create an issue in their tracker. If not please follow the https://github.com/guylabs/ion-autocomplete#guidelines-to-report-an-issue to update this issue.

Thanks and regards

Guy

**Comment by joesleiman** [comment]
where can i submit an issue ? not related to ion-autocomplete

**Comment by guylabs** [comment]
This is the official Ionic repository: https://github.com/driftyco/ionic
