### ISSUE TITLE
How can i set the value of the selected item as searchQuery

### ISSUE THREAD

**Issue by BioPhoton** [guylabs/ion-autocomplete#193]
In the google maps app on android the searchQuery value changes to the formatted address of the selected search item. 
How can i achieve this with your module?

I can see that you reset the searchQuery value when closing the modal. => 
https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L148

**Comment by guylabs** [comment]
Hi @BioPhoton,

sorry for my delay but I was on a longer trip and now I am working partially.

As of now there is a new property called `clear-on-select` with which you do not clear the model: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L149.

Does that help you out? If not I think that the #28 is helping out as there you can hook into the rendering and then render the proper format.

Does this answer your question?

Thanks and regards,

Guy

**Comment by BioPhoton** [comment]
I solved this with another workaround, will compare it with your suggested solution. Thx!

**Comment by BioPhoton** [comment]
When do you think 0.3.3 is ready?

**Comment by guylabs** [comment]
Hi @BioPhoton 

well I do not know. I am still abroad and do not know when I am able to work on it again but I hope I am able in November 16.

Thanks and regards,

Guy
