### ISSUE TITLE
Use collection-repeat instead of ng-repeat

### ISSUE THREAD

**Issue by ziv-moonsite** [guylabs/ion-autocomplete#194]
Hi
Great plugin.
In large data sets the performance isn't good enough.
i recommend using collection-repeat instead of ng-repeat for the data presentation.

Thank.

Ziv

**Comment by guylabs** [comment]
Hi,

sorry for my delay but I was on a longer trip and now I am working partially.

Well there were several issues (#94 #64 #136 and more) with the `collection-repeat` and therefore we now use the `ng-repeat`.

If you want to use the `collection-repeat` you can always add your own custom template to do so. See https://github.com/guylabs/ion-autocomplete#template-url. Therefore I will close this issue as the solution is to create your own template.

Thanks and regards,

Guy
