### ISSUE TITLE
Is it possible to ues expressions for itemValueKey and  itemViewValueKey

### ISSUE THREAD

**Issue by BioPhoton** [guylabs/ion-autocomplete#195]

**Comment by BioPhoton** [comment]
I wrap your directive with my custom once. 
In my directive there is a flag that decides what value to use for itemValueKey and itemViewValueKey. 
Is it possible to use some kind of expression or so in for this attributes? => {{myItemViewValueKey}}

**Comment by guylabs** [comment]
Hi @BioPhoton 

well you mean that the expression would resolve to a `itemViewValueKey` which is then applied to the result JSON of the `items-method` right with the help of the `$parse` service? See here: https://github.com/guylabs/ion-autocomplete#using-expressions-in-value-keys

Thanks and regards,

Guy

**Comment by BioPhoton** [comment]
I will try this. Thx!

**Comment by BioPhoton** [comment]
Do you have any code example for this?

**Comment by guylabs** [comment]
Hi @BioPhoton,

well in the documentation is a code sample. Not a running one but some snippets which should work. Does it not work on your side? If not could you maybe create a codepen with the not working example?

Thanks and regards,

Guy
