### ISSUE TITLE
Cannot make the ion-autocomplete closing, with cancel/done button (Ionic 1.3.1)

### ISSUE THREAD

**Issue by itamair** [guylabs/ion-autocomplete#199]
I am working with Ionic 1.3.1 and have to implement autocomplete functionalities with Google Places Apis, so I am trying / assessing this directive.
My markup is the following:

`<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete" autocomplete="off" ng-model="markers.mainMarker.address"
         max-selected-items="1"
         item-view-value-key="formatted_address"
         items-method="getAddressSuggestions(query)"
         />`

The results selection seem to work properly, but I am not able (and even figure out) how to close the popup/modal once I have done. 
In the default scenario I was even unable the catch the presence of the default cancel ("Done") button, because the default directive css was keeping it hidden / transparent in my case,
so I had override that rule with this css lines of code:

`.ion-autocomplete-cancel.button-clear.button-clear {
  color: black;
}
`
With this, the "Done" button appears ... but once clicked it doesn't trigger any event on the model, that keeps open, and everything stays stick unusable. If I click on the input ion-autocomplete element (on the background) the modal loses the focus, and the scenario becomes even worse, and unusable (screenshot attached about this). 

![schermata 2016-08-17 alle 11 07 29](https://cloud.githubusercontent.com/assets/1429859/17731371/3f475b14-646d-11e6-8f89-da00c1f01b21.jpg)

I have verified from this issue #155 (and this codepen: http://codepen.io/anon/pen/bprxwd) that the default Cancel functionality should work without any added callback method on it. Isn't it?

What am I doing wrong? 
Might this be just a matter of Ionic version incompatibility? 
Tnx in advance ...

**Comment by guylabs** [comment]
Hi @itamair,

thanks for reporting the issue. I will first need to upgrade the Ionic version to the latest 1.3.x. See issue #189. After that I will check it again and come back to you.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @itamair 

could you maybe restest with the latest master version again as there it now uses Ionic `1.3.2` and I could not reproduce it.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @itamair 

any news on this?

Thanks and regards

Guy

**Comment by guylabs** [comment]
I will close the issue due to inactivity. You can reopen it any time.

Thanks and regards,

Guy
