### ISSUE TITLE
Issues with the Callback Method $http.get

### ISSUE THREAD

**Issue by parveensaini5** [guylabs/ion-autocomplete#202]
First of all Thank You for this great directive.

I am facing issues with the callback method. 

I want to pre populate the items from a webservice, but before display, I want to store them in a service for search. The webservice returns the data, but the items are not being displayed in the Modal window.

**WORKING METHOD**
```
var ajaxResult = [];
$scope.callbackMethod = function (query, isInitializing) {
	if(query != '') {
		return filter('filter')(ajaxResult.slice().reverse(), query);
	} else {
		return $http.get(endpoint);
	}
}
```

**NOT WORKING**
```
$scope.callbackMethod = function (query, isInitializing) {
	if(query != '') {
		return filter('filter')(ajaxResult.slice().reverse(), query);
	} else {
		$http.get(endpoint).success(function(response) {
			// Store data in a service before display
			Location.initData(response.data);
			return response.data;
		});
	}
}
```
This feature is also required for pagination/infinite scrolling.

Thank you in advance for your kind assistance

**Comment by guylabs** [comment]
Hi @parveensaini5,

well you need to create a deferred object, resolve it in the success method and then return a promise after the success method instead of returning the response data inside the success method. Then this should work properly.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @parveensaini5 

I will close the issue now due to inactivity. If you have any comments please add them here and we can reopen it.

Thanks and regards,

Guy
