### ISSUE TITLE
Hide loading spinner in finnaly block

### ISSUE THREAD

**Issue by BioPhoton** [guylabs/ion-autocomplete#203]
Now the loading spinner hides only if the request resolves. This is bad for rejected requests. 
pleas move the state change into the finally block of the promise.

THX!

**Comment by guylabs** [comment]
Hi @BioPhoton 

this has already been done in this commit https://github.com/guylabs/ion-autocomplete/commit/c80103e98dd949e535f1faa3558d76b42494b1b4. So I will close this as fixed.

Thanks and regards,

Guy
