### ISSUE TITLE
I can't get the grunt task run...I tried on mac and windows. Getting:

### ISSUE THREAD

**Issue by sebrojas14** [guylabs/ion-autocomplete#204]
![image](https://cloud.githubusercontent.com/assets/1771574/18651613/f51e445a-7e91-11e6-8048-92346c5d8fdb.png)

Please help, I already make serious improvements to tyhe library but I can't build to send a pull request

**Comment by guylabs** [comment]
Hi @sebrojas14 

what kind of NPM and Node version are you using?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @sebrojas14 

can you maybe try it with Node 5.x and NPM 3.x? There it should work properly as I updated to this some time ago.

Thanks and regards,

Guy

**Comment by sebrojas14** [comment]
Now, after update npm and node, grunt tasks are working. Now I have a problem with tests. The method getSearchInputElement is not working, because now i'm using ionicModal. But I dont't now how to modifiy that method

**Comment by guylabs** [comment]
HI @sebrojas14 

well you need to adapt all the protractor tests to incorporate the move to the `ionicModal`. This is a cumbersome task as all tests now are based on the standard way. Do you want to creaet a fork where the `ionicModal` is used?

I cannot give you much support if you want to change the whole structure of the component as I need the time to fix the current issues ;). But you can always ask here and I see how I am able to help out.

But the Grunt task is now running so we can close the issue right?

Thanks and regards,

Guy

**Comment by sebrojas14** [comment]
I have a branch in my fork (https://github.com/Hobbule/ion-autocomplete) with the ionicModal. The change is small, but I don't know how to modify that test method, any hel from you or the community is welcome

**Comment by guylabs** [comment]
Hi @sebrojas14 

you mean this method here right?  https://github.com/guylabs/ion-autocomplete/blob/master/test/ion-autocomplete.single-select.spec.js#L463

Well you need to get the proper query selector based on the new structure with your Ionic Modal service (this can differ from the one I use). See http://www.w3schools.com/jsref/met_document_queryselector.asp. You can test that in your browser to get the input field and then you can add that in the test.

You can also debug the protractor tests like this here: https://github.com/angular/protractor/blob/master/docs/debugging.md

With these tips you should be able to fix it.

I will now close the issue as the you are now able to run Grunt etc. and we can still discuss here. Maybe you can also ask on Stackoverflow as there you have a more active community which is willing to help.

Regards,

Guy

**Comment by sebrojas14** [comment]
Ok, as soon as I have time I'm gonna give it a try
