### ISSUE TITLE
Undesired automatic selection when mouse-clicking

### ISSUE THREAD

**Issue by flowli** [guylabs/ion-autocomplete#205]
Hey folks,

first off: thanks for making this awesome module!
There's only one thing that makes user experience less than optimal: when I mouse-click on a field and no item is pre-selected, it selects the very item (that happens to be there) below the mouse pointer "on mouse-up" (I don't release the mouse button and click again!).
I made an animated GIF from my observation:
![test](https://cloud.githubusercontent.com/assets/2144428/18895195/14f94964-8518-11e6-9c5b-20ef3b1a310f.gif)
Do you know how that comes, or even better, how to switch this behaviour off?

Thanks in advance!
Flo(w)

**Comment by guylabs** [comment]
Hi @flowli 

looks like the `ng-click` also fires when a `mouseUp` event is created. Could you maybe create a custom template and turn off the `mouseUp` by adding a https://docs.angularjs.org/api/ng/directive/ngMouseup attribute to the line https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L98 on the `ion-item`? If this works you could create a PR and I could merge it as currently I do not have much time working on the directive.

Thanks and regards,

Guy

**Comment by flowli** [comment]
Hi @guylabs thank you very much for the pointer. I made this work a little different, simple by using ng-mousedown instead of ng-click. It works on Android and - most importantly - also on Chrome on MacOS. So a PR is not needed I guess, you can just exchange one for the other event and see if people complain :-p Work flawlessly here, however.

**Comment by flowli** [comment]
After ng-mousedown does not work on the windows platform, I needed to research this in more depth. It looks better to leave ng-click in place but remove modal opening event focus from
`element.bind('touchend click focus', onClick);`. Seems like the focus event is absorbed by opening the modal while the mouseup triggers click on the item below.
