### ISSUE TITLE
bower install ion-autocomplete --save No command 'bower' found

### ISSUE THREAD

**Issue by Boasbabs** [guylabs/ion-autocomplete#207]
Hello,

I am trying to add ion-autocomplete to an existing ionic app but i get that error when i try to install ion-autocomplete through bower.

> $ bower install ion-autocomplete --save
No command 'bower' found, did you mean:
 Command 'boxer' from package 'boxer' (universe)
bower: command not found

this is what shows up in my terminal.

PS. I am new to ionic framework and angular.

**Comment by guylabs** [comment]
Hi

you first need to install [bower](https://bower.io/#install-bower) and then this should work out of the box.

If this does not fix it you can reopen the issue and add a comment.

Thanks and regards,

Guy
