### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by ltung** [guylabs/ion-autocomplete#209]
I tried to implement the ion-autocomplete and I am stuck in these 2 problems:

1. Is there a way that one can "select" an item but still can change/type the search text? In other words, the search box, beside the selected item, can also type anything?

2. In the "suggestion", can it be a template so that, e.g., I could include a picture inside the suggestion.

**Comment by guylabs** [comment]
Hi @ltung 

I do not understand your first question: what exactly do you want to achieve? 

And for the second question you can change your template with a custom one and add your pictures etc.: https://github.com/guylabs/ion-autocomplete#template-url

Thanks and regards,

Guy

**Comment by ltung** [comment]
Thanks for your answer.

For question 1, say, if we go to search in Google, it provides some suggestion while typing our search text, after we select the suggestion, we can still type in more search text of even change the suggested text.

**Comment by guylabs** [comment]
Hi @ltung 

Well that is not possible. You can only search and then select it. There is no suggestion mechanism.

I will close the issue as I think your questions are answered and the suggestion feature is not planned at all yet.

Thanks and regards,

Guy
