### ISSUE TITLE
I cant get autocomplete to work in my project

### ISSUE THREAD

**Issue by Heechan79** [guylabs/ion-autocomplete#21]
Hi,
I am using the autocomplete but facing some problems when running it in the ios and android emulator. Beforehand I made a mockup running it in the browser and this worked fine, but when copying the code to my actual project I got a error. Could you please help me.. dont have any clue!
The following error I got in the console:
[Error] Error: collection-repeat expected attribute collection-item-height to be a an expression that returns a number (in pixels) or percentage. 

this is my code:
HTML
        <div class="list card ">
            <ion-autocomplete ng-model="model"
                item-value-key="view"
                item-view-value-key="name"
                item-view-value-key="id"
                items-method="getTestItems(query)"
                items-method-value-key="items"
                placeholder="Zoek hier naar een evenement"
                items-clicked-method="itemsClicked(callback)"
                select-items-label="zoek"
                selected-items-label="Selected:"/>
        </div>

JS
$scope.getTestItems = function (query) {
        console.log('regel 76');
        var searchItems = [
            {id: "1", name: "John", view: "John: "},
            {id: "2", name: "Steve", view: "Steve: "},
            {id: "3", name: "Richard", view: "Richard: "},
        ];
        var returnValue = { items: [] };
        searchItems.forEach(function(item){
            console.log('bijna onderaan');
            console.log(item);
            if (item.name.indexOf(query) > -1 ){
                returnValue.items.push(item);
            }
            else if (item.id.indexOf(query) > -1 ){
                returnValue.items.push(item);
            }
        });
        return returnValue;
    };
    $scope.itemsClicked = function (callback) {
        $scope.callbackValueModel = callback;
    }

**Comment by guylabs** [comment]
Hi,

what kind of ionic version are you using in your project? The autocomplete component is using `1.0.0.rc3` and with this version it should work without any issue.

Could you please try and give me feedback?

Thanks and regards,

Guy

**Comment by Heechan79** [comment]
Updating did the job! Thanks

**Comment by guylabs** [comment]
Nice that this was the issue. I will add an overview to the documentation which Ionic version is needed for which ion-autocomplete version.
