### ISSUE TITLE
display results in main page and not in modal

### ISSUE THREAD

**Issue by dario-colombo** [guylabs/ion-autocomplete#211]
hi, i wonder if there is the possibility to show the result list directly in the page where the input reside, without opening the modal, or rather integrate the  modal code into the main page.thank you

**Comment by guylabs** [comment]
Hi @dario-colombo 

well this would be the best solution for this kind of component (like all other autocomplete components for the web). But for this project this would be an overkill and we should wait till Ionic has such a configurable component. (something similar: http://ionicframework.com/docs/v2/components/#searchbar)

Thanks for the question but I think I won't do this for now.

Regards,

Guy
