### ISSUE TITLE
Closing ion-autocomplete-container using android hardware back button not firing callback passed to "cancel-button-clicked-method" attribute?

### ISSUE THREAD

**Issue by sunny061** [guylabs/ion-autocomplete#212]
Hi,

Thanks for the great work on this directive. I was wondering if it's the default behavior for the "cancel-button-clicked-method" callback to not fire when the autocomplete container is closed using a hardware back button on android? If it is, may I know how I can trigger a callback function when the autocomplete container is closed without tapping the done/cancel button but by the hardware back button. I have tried overriding the back button but my custom backbutton handler also doesn't fire when the autocomplete container is open. Thanks

I am developing on ionic version 2.0.0 and ion-autocomplete version 0.3.2.

Regards

**Comment by guylabs** [comment]
Hi @sunny061 

well Ionic version `2.0.0` is not supported by now. I first need to fix some issues with Ionic `1.3.x` before we can move to `2.0.0`.

I never tested it and I think the back button does not call the callback as when you would press the done button. What use case do you have when the user clicks the back button to close the popup?

Thanks and regards,

Guy

**Comment by sunny061** [comment]
Hi @guylabs 

Sorry. The project that I am working on is actually using Ionic 1.3.1. Ionic 2.0.0 is the CLI version installed on my pc so thats my bad. 

And regarding my use case, the way I use the directive is that when a user taps the search input it opens it in full screen. And the user naturally uses the hardware back button on android to go back to the previous screen. I tried to override the back button event in cordova/ionic to fire the same logic I have in the cancel-button-clicked-method, but it didn't fire. I will do some more trial and error though. It's possible that I might have missed something.

**Comment by guylabs** [comment]
Hi @sunny061 

and could you get it to work? If yes please elaborate more on how you fixed it as then I could add it to the project or at least to the documentation.

Thanks and regards

Guy

**Comment by sunny061** [comment]
Hi @guylabs, I did manage to get it working by successfully overriding the hardware back button and calling the cancel-button-clicked method myself. I will share the code once I get back on my pc.

**Comment by guylabs** [comment]
Hi @sunny061 

could you maybe create a pull request with your adaptions? As the #216 is requesting the same thing so you could provide the solution if you want to.

I would really appreciate this and others could also use it.

Thanks and regards,

Guy

**Comment by sunny061** [comment]
I actually solved my issue by using the following code in my ionic 1 project...

````
$ionicPlatform.onHardwareBackButton(function() {
  // call cancel-button-clicked-method callback function
});
````
Also, this stackoverflow helped me learn about overriding the back button behavior correctly.
http://stackoverflow.com/a/32246017/1874266

**Comment by guylabs** [comment]
HI @sunny061 

thanks for sharing your solution!

Regards

Guy
