### ISSUE TITLE
dynamically change text on ion-autocomplete

### ISSUE THREAD

**Issue by vvavepacket** [guylabs/ion-autocomplete#213]
How do we change the text inside an ion-autocomplete? I know it is binded on $scope.model, but changing the $scope.model doesn't affect the content of the ion-autocomplate.  We can change the text by selecting an item from the list, but how to do this dynamically? Without actually the user activating the ion-autocomplete?

**Comment by guylabs** [comment]
Hi

I am sorry for the late response but I could not reply earlier. 

Well you can pre populate the model as written here: https://github.com/guylabs/ion-autocomplete#the-model-to-item-method

But why do you want to pre populate the component and the user is not able to select anything. Then you could also use a deactivated input field. Or is there another use case behind this?

Regards,

Guy

**Comment by guylabs** [comment]
Hi

any news on this? I will close the issue now due to inactivity. If you still have some comments or other inquiries, then please comment and reopen the issue.

Thanks and regards,

Guy
