### ISSUE TITLE
Multiple directives - asking for new/isolated scope

### ISSUE THREAD

**Issue by royalcheeseburger** [guylabs/ion-autocomplete#217]
Hi there,

I don't know much if it more an issue in my code than I bug but...

`<input ion-autocomplete type="text"
              readonly="readonly"
              class="ion-autocomplete"
              autocomplete="off"
              max-selected-items="1"
              item-value-key="name"
              items-method="getSportItems()"/>`

I have a ng-controller attached to the body of my page.

I get the following error when running my code:

`[$compile:multidir] Multiple directives [input (module: app.directives), ionAutocomplete] asking for new/isolated scope on: <input ion-autocomplete="" type="text" readonly="readonly" class="ion-autocomplete ng-pristine ng-untouched ng-valid" autocomplete="off" max-selected-items="1" item-value-key="name" items-method="getSportItems()">`

Looks like there is a conflict between the input directive defined in app.directives and ion-autocomplete... am I doing something wrong or is it a bug?

Thanks for your help and reactivity !

**Comment by guylabs** [comment]
Hi

can you maybe go through this guide https://github.com/guylabs/ion-autocomplete#guidelines-to-report-an-issue and then maybe create a codepen where you can reproduce the issue with some parts of your application? It is very hard to analyse if I am not able to reproduce it.

Thanks and regards,

Guy

**Comment by royalcheeseburger** [comment]
Hi Guy,

The error came from me, my mistake...

Thanks,

Burger

**Comment by lucamorelli** [comment]
I'm having the same problem
`lib.js:26799 Error: [$compile:multidir] Multiple directives [input, ionAutocomplete] asking for new/isolated scope on: <input ion-autocomplete="" type="text" readonly="readonly" class="ion-autocomplete ng-pristine ng-untouched ng-valid" autocomplete="off" ng-model="profile.provinceToSearchFor" max-selected-items="1" items-method-value-key="items" items-method="getProvince(query)">
`
but looks like is conflicting with the angular input directive. How can I solve this?
