### ISSUE TITLE
Search as inline rather than modal popup

### ISSUE THREAD

**Issue by amalfernando** [guylabs/ion-autocomplete#218]
Hi,
This directive is awesome and very useful. This is not a issue. I don't no where to ask this question. 

All I need is ion-autocomplete to use in a page without modal popup. Is there any way to achieve this. If so can someone give me a direction. Code sample would be handy.

Thanks

**Comment by guylabs** [comment]
Hi @amalfernando 

thanks for the praise ;). Well you could change the default template with this property: https://github.com/guylabs/ion-autocomplete#template-url and provide your own template. This should work.

Thanks and regards

Guy

**Comment by amalfernando** [comment]
wow that was a quick response. thanks Guy u r da best.

**Comment by guylabs** [comment]
Good that I could help. I will close the issue and you can add a comment if there is anything more about it.

Regards,

Guy
