### ISSUE TITLE
Animate open and close modal

### ISSUE THREAD

**Issue by nlarche** [guylabs/ion-autocomplete#219]
Hi,

is there a way to add class when the modal is open
and remove a class when the modal is close ?

I think it might be better to change 
`.css('display', 'block');` by  `.addClass(openClass)` Line 304
`.css('display', 'none');` by  `removeClass(openClass)` Line 329

What do you think about that ?

**Comment by guylabs** [comment]
HI @nlarche 

well this could be a nice enhancement such that you could set the css when it opens and when it closes. Maybe a hook where you receive the element and then you can override the default CSS with your custom one.

Currently I do not have much time for new features. Maybe you could come up with a pull request?

Thanks and regards,

Guy
