### ISSUE TITLE
Pre-population of Selected items

### ISSUE THREAD

**Issue by patrickian** [guylabs/ion-autocomplete#223]
Hi! Sorry, Im a bit new to this library. I cant make the pre-population of the selected items work. Can anyone help me? Thank you, appreciate it!

**Comment by guylabs** [comment]
Hi @patrickian 

did you already check the following part in the documentation: https://github.com/guylabs/ion-autocomplete#the-model-to-item-method ?

If yes please go ahead and follow this section on how to report an issue: https://github.com/guylabs/ion-autocomplete#guidelines-to-report-an-issue

Thanks and regards

Guy

**Comment by guylabs** [comment]
Hi @patrickian 

any news on this?

Thanks and regards

Guy

**Comment by patrickian** [comment]
Its a bit wierd though. its working perfectly if there is some existing data thats going to be pre- populated. but if there is nothing to pre-populate, its creating a blank entry in the suggestions/history.
sorry for the late response @guylabs

**Comment by patrickian** [comment]
gonna close this because no one's responding anyway.thanks!
