### ISSUE TITLE
How to set ion-autocomplete non-case sensitive

### ISSUE THREAD

**Issue by aafarhadi** [guylabs/ion-autocomplete#224]
my data like: Alaska, Sydney, .....

when i press A, Alaska show up, but when i press a, Alaska wont show

i want to when i press A or a, Alaska show up

how to solve this?

**Comment by guylabs** [comment]
Hi @aafarhadi 

you need to implement this case insensitive logic in you `items-method` (see https://github.com/guylabs/ion-autocomplete#the-items-method). There you can always transform the query parameter to lower case and then have your data array with lower case letters. Then you can search for both types.

Thanks and regards,

Guy

**Comment by aafarhadi** [comment]
Thanks, its work

owsome :)
