### ISSUE TITLE
Failed to load the ion-autocomplete package

### ISSUE THREAD

**Issue by jessicafenty** [guylabs/ion-autocomplete#228]
I installed the package on Atom and gave the following error:
Failed to load the ion-autocomplete angular package is not defined.
How can I fix this?

**Comment by guylabs** [comment]
Hi @jessicafenty 

please follow the https://github.com/guylabs/ion-autocomplete#guidelines-to-report-an-issue guidelines. And what means "you installed it on Atom" ? Can you tell me how to reproduce it?

Thanks and regards

Guy
