### ISSUE TITLE
Ability to pass sort of id to the item-method

### ISSUE THREAD

**Issue by lhrolim** [guylabs/ion-autocomplete#23]
Hi,

I´m starting to use the component, but I think it misses the hability to build the query based upon some key, besides the text itself.

I´m not sure, if there´s any suggested workaround though, please let me know. 

I´ll try to explain it:

Suppose, for instance, that I have one screen with 2+ components, and that for each of them the query should be created differently.

The screen is also generated dinamically, on a ng-repeat, based upon a JSON structure, so I can´t really declare the html on 2 different ways (calling 2 different functions).

Instead, I´d rather have something like that (just a suggestion)

<input ng-switch-default type="text" ng-model="datamap[field.attribute]" items-method="associationsSearch(query,identifier)" id="{{field.attribute}}">

Ideally this second attribute should be optional, so that there´s no API incompatibility.

We could also make it a single queryParameter attribute:

queryParameter:
{
query:'xxx'
id: '123'
}

But I sense this would be undesirable for most cases

So that, both the query string and a identifier of the component are passed to the callback function. This way, I would have means of knowing how to build the proper query.

A "this" reference to the element could also solve it, but it feels a little overkill for the task.

Is there any workaround for it?

Thanks

**Comment by guylabs** [comment]
Hi,

yes I see your issue, but currently there is no workaround for this. What I could do is to add a `itemsMethodId` attribute to be able to add an id for the ìtemsMethod`such that you can set this attribute for each component in the ng-repeat. Then I would add it to a query object which is then passed to the `itemsMethod` such that you can get the id and the query of the component. What do you think about this solution?

Thanks for mentioning it.

Regards.

**Comment by lhrolim** [comment]
Yes, that´s pretty much what I´ve done here on the code too.

Do you want me to do a pull request further?

    var promise;
                            if (!scope.identifier) {
                                // convert the given function to a $q
promise to support promises too
                                promise =
$q.when(compiledTemplate.scope.itemsMethod({ query: query }));
                            }
                            else {
                                var queryParameters = {
                                    query: query,
                                    identifier: scope.identifier
                                }
                                // convert the given function to a $q
promise to support promises too
                                promise =
$q.when(compiledTemplate.scope.itemsMethod({ queryparameters:
queryParameters}));
                            }

btw: The other issue I mentioned, had nothing to do with the components,
but with trying to invoke a function inside a directive; it´s something odd
about the angularjs structure of my classes.
But got it working moving it to the controller (not the directive´s
controller)

Thanks

**Comment by lhrolim** [comment]
I think I might need it on other callbacks methods, so that´s why I suggested a generic "identifier" instead of a simply itemMethodsId

**Comment by guylabs** [comment]
Ok thanks for that. You mean that you will also need it in the clicked item callback right? I can implement it in both places and then finally release 0.2.2.

**Comment by lhrolim** [comment]
Ok. That would be awesome.

Thanks

**Comment by guylabs** [comment]
Hi,

I just added the new functionality. Please checkout the following documentation links:

https://github.com/guylabs/ion-autocomplete#component-id
https://github.com/guylabs/ion-autocomplete#the-items-method
https://github.com/guylabs/ion-autocomplete#the-items-clicked-method

There you will find how to use it. You can get the latest changes with bower if you follow this guide:

http://guylabs.ch/2015/05/08/get-latest-master-changes-of-a-bower-dependency/

Can you please test it in your project such that we can close the issue and then release 0.2.2?

Thanks and regards.
