### ISSUE TITLE
model-to-item-method doesn't work properly

### ISSUE THREAD

**Issue by kamranata** [guylabs/ion-autocomplete#230]
Hi,

I cant edit predefined model using promise function in model-to-item-method attribute. Becouse on your code 

` var resolveAndSelectModelItem = function (modelValue) {
                        // convert the given function to a $q promise to support promises too
                        var promise = $q.when(ionAutocompleteController.modelToItemMethod({modelValue: modelValue}));

                        promise.then(function (promiseData) {
                            // select the item which are returned by the model to item method
                            ionAutocompleteController.selectItem(promiseData);
                        }, function (error) {
                            // reject the error because we do not handle the error here
                            return $q.reject(error);
                        });
                    };`
you send object returned by promise to selectItem. 
`ionAutocompleteController.selectItem(promiseData);`

But must send like this
`ionAutocompleteController.selectItem(promiseData.data);`

I changed it for myself. Please do this changes on your code to

**Comment by guylabs** [comment]
Hi @kamranata 

I see your point but then you need to change your `model-to-item` method to return the `promiseData.data` directly and then it will work as well. Then you do not need to patch the library and  I do not need to change this as this worked for all others.

How does your `model-to-item` method look like? What do you return there exactly? Can you maybe paste it here?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
I will close the issue due to inactivity. You can reopen it any time.

Thanks and regards,

Guy
