### ISSUE TITLE
ion-autocomplete exec on-click and not in tag input

### ISSUE THREAD

**Issue by ziobudda** [guylabs/ion-autocomplete#233]
Hi, i'm using ion-complete in my app and it works very well. Now I need to use it in another app but in this app I need to start ion-autocomplete on a "on-tap" event and not link in a <input> tag. 

Is this possible ? 

Thanks.

**Comment by guylabs** [comment]
Hi @ziobudda 

sorry for the delay but I could not get to you earlier. Well what do you mean with "link in a tag"? Normally the component opens on a `onclick` event (see https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L420). 

You can also use the manage externally (see https://github.com/guylabs/ion-autocomplete#manage-externally) and create your own `ontap` handler and then open the modal. Would that work for you?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @ziobudda 

any news on this? I will close the issue due to inactiviti and you can reopen it again if there is something unclear.

Thanks and regards

Guy
