### ISSUE TITLE
at android device not working

### ISSUE THREAD

**Issue by kotran88** [guylabs/ion-autocomplete#234]
I changed some code to get data from json file. 
on web like chrome, it work fabulously well. but not on android device. 
I get alert saying "s" but not next. 
maybe there is a problem on observable map?

```
getResults(keyword:string):Observable<any> {
    console.log("keyword 22233: "+keyword);
    alert("s");
    return this.http.get('/assets/metro.json')
      .map(
        result =>
        {
          alert(result.json().DATA);
          console.log(result.json().DATA.filter(item => item.STATION_NM.toLowerCase().startsWith(keyword.toLowerCase()) ))
          return result.json().DATA
            .filter(item => item.STATION_NM.toLowerCase().startsWith(keyword.toLowerCase()) )
        });
```

**Comment by guylabs** [comment]
Hi @kotran88 

sorry for the delay but I could not get to you earlier. Can you maybe add a stacktrace where exactly this error happens? And could you maybe also add the configuration of the component?

See https://github.com/guylabs/ion-autocomplete#guidelines-to-report-an-issue

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @kotran88 

any news on this? I will close the issue due to inactiviti and you can reopen it again if there is something unclear.

Thanks and regards

Guy
