### ISSUE TITLE
How to disable only one or more items, not all item,  in ion-autocomplete

### ISSUE THREAD

**Issue by tunathoni** [guylabs/ion-autocomplete#239]
Hi al, i already use ion-complete, but i want to know how to disable only one or more items, not all item,  in ion-autocomplete, is it possible ?

**Comment by guylabs** [comment]
Hi @tunathoni 

this is currently not possible to disable items. What you can do is to filter them out in your `items-method` and do not show them to the user at all.

Does that answer your question?

Thanks and regards

Guy

**Comment by tunathoni** [comment]
Hi @guylabs , 

Thanks for your response, but i already customized your plugin, feel free to look at my repo. it possible to disable some items, with additional parameter. so you can look at [My Repo](https://github.com/tunathoni/ion-autocomplete).

Thanks a lot for your repo.

Thoni.
