### ISSUE TITLE
Clear data from the outside

### ISSUE THREAD

**Issue by blueprint1985** [guylabs/ion-autocomplete#240]
Hello team!

First, thanks for a really nice application.

I'm wondering how I can clear a field from the an external controller function. My issue is that I have the autocomplete field inside a form, and when I submit the form, I clear all scope-variables that the form uses, but the autocomplete-field is still filled in with the previous value. I would like it to be cleared when I submit the form.

The field:

```                        <!-- Required fields part -->
                        <div class="item borderBottom" ng-class="'details-list-item-' + colorMode">
                            <div class="variable" ng-class="'details-list-variable-' + colorMode">
                                KATEGORI<span class="mandatory-marker">*</span></div>
                            <input ion-autocomplete type="text"
                                   ng-model="selectedCategory"
                                   ng-required="true"
                                   autocomplete="off"
                                   ng-disabled="isUpdate"
                                   placeholder="VÄLJ..."
                                   cancel-label="GJORT"
                                   max-selected-items="1"
                                   item-view-value-key="name"
                                   items-clicked-method="categorySelected(callback)"
                                   template-url="views/shared/autocomplete-modal.html"
                                   class="value noBackground noBorders fullWidth ion-autocomplete"
                                   ng-class="'details-list-input-' + colorMode"
                                   items-removed-method="requiredFieldRemoved()"
                                   items-method="autocompleteCallbackMethod(query, $root.displayCategories, 'name')"/>

                        </div>
```

The items method:

```
    $scope.autocompleteCallbackMethod = function (query, data, fieldName, orderBy) {
        var filtered = [];
        data.forEach(function(item){
            if(item[fieldName] && item[fieldName].toLowerCase().indexOf(query.toLowerCase()) !== -1){
                filtered.push(item);
            }
        });
        return orderBy ? $filter('localeOrderBy')(filtered, orderBy, false) : filtered;
    };
```

After sending the form I do this: `$scope.selectedCategory = null;`

But the field is still filled out.

**Comment by guylabs** [comment]
Hi @blueprint1985 

thanks for the detailed issue description. Please have a look at the https://github.com/guylabs/ion-autocomplete#external-model documentation. There you can set an additional variable and then you can clear the component by assigning an empty array to the variable.

 Regards,

Guy

**Comment by blueprint1985** [comment]
@guylabs Thanks for your quick answer.

It worked fine on a couple of static fields that I have. But then I ran into another problem.

Consider the following

```
<div ng-repeat="customField in template.customFields"
     ng-if="categoryIsSelected"
     class="item borderBottom"
     ng-class="'details-list-item-' + colorMode">

    <input ion-autocomplete type="text"
           ng-if="customField.type === 'List'"
           ng-model="customField.viewValue"
           ng-required="customField.required"
           autocomplete="off"
           placeholder="VÄLJ..."
           cancel-label="GJORT"
           max-selected-items="1"
           item-view-value-key="value"
           items-clicked-method="customFieldSelected(callback, customField)"
           item-value-key="id"
           template-url="views/shared/autocomplete-modal.html"
           class="value noBackground noBorders fullWidth ion-autocomplete"
           ng-class="'details-list-input-' + colorMode"
           items-method="autocompleteCallbackMethod(query, customField.values, 'value', 'value')"
           external-model="externalCustomFields[customField.name]"
           />

  </div>
```

As you see, I use a repeat to print the fields. `template.customFields` may have several different fields in advance, and I don't know exactly how many or their name for each template. I many different templates. You can see that I added `external-model="externalCustomFields[customField.name]"` and in my controller on the submit method, I added `$scope.externalCustomFields = [];`. I also tried `$scope.externalCustomFields = {};`. Do you know what I need to do to clear those fields also upon form submission?

Best regards
Martin

**Comment by guylabs** [comment]
Hi @blueprint1985 

the values stored in the `externalCustomFields[customField.name]` are objects (`{...}`) right? I am not sure about the data binding of Angular with arrays and maybe you need to iterate through the array and then set each element to an empty array `[]`. 

Does that help?

Regards

Guy

**Comment by guylabs** [comment]
Hi @blueprint1985 

any news on this? I will close the issue due to inactiviti and you can reopen it again if there is something unclear.

Thanks and regards

Guy
