### ISSUE TITLE
autocomplete automatically shown while opening view

### ISSUE THREAD

**Issue by lucamorelli** [guylabs/ion-autocomplete#241]
I tried a few times to add this component to a view using both the samples here or [this sample](https://codepen.io/guylabs/pen/GJmwMw) but I obtain always the same result: when I open the view the autocomplete dialog si shown at full screen covering the orginal page, and even pressing the Done button disappear.
What am I doing wrong?

**Comment by guylabs** [comment]
Hi @lucamorelli 

cool that you could fix it by yourself.

Thanks for using the component and regards

Guy
