### ISSUE TITLE
How to load from List or array values in Autocomplete?

### ISSUE THREAD

**Issue by PrabuGovindan** [guylabs/ion-autocomplete#242]
how to Load from List or array values in Autocomplete?

**Comment by guylabs** [comment]
Hi @PrabuGovindan 

Please have a look at the https://github.com/guylabs/ion-autocomplete#the-items-method documentation or have a look at the tests here https://github.com/guylabs/ion-autocomplete/blob/master/test/ion-autocomplete.single-select.spec.js#L216 (there are others as well using static defined lists/maps).

Thanks and regards

Guy

**Comment by guylabs** [comment]
any news on this? I will close the issue due to inactiviti and you can reopen it again if there is something unclear.

Thanks and regards

Guy
