### ISSUE TITLE
number\size of records

### ISSUE THREAD

**Issue by eranya** [guylabs/ion-autocomplete#243]
Hi,

Before using this lib, can you please tell me how many records this lib support and the size of data?
I need to develop mobile app in ionic for ios and android. 

Thanks,

**Comment by guylabs** [comment]
Hi @eranya 

I did not implement any performance tests, but the components are standard Ionic components and therefore you can also check the Ionic forums for such performance tests. Please check #238 about the infinite scroll from Ionic which has better performance than the current implementation.

Does that answer your question?

Thanks and regards

Guy

**Comment by guylabs** [comment]
any news on this? I will close the issue due to inactiviti and you can reopen it again if there is something unclear.

Thanks and regards

Guy
