### ISSUE TITLE
where i need to add dependecncy ?

### ISSUE THREAD

**Issue by sivajik34** [guylabs/ion-autocomplete#246]
in which file can i add following dependency?
angular.module('myApp', [
  'ionic',
  'ion-autocomplete'
]);

**Comment by guylabs** [comment]
Hi @sivajik34,

it depends on your project setup and the structure. You can have a look here how the end to end test was set up: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.multiple-select.e2e.html or just check the Angular documentation on what they have for best practices. 

Regards,

Guy
