### ISSUE TITLE
added extra fields in custom template

### ISSUE THREAD

**Issue by sivajik34** [guylabs/ion-autocomplete#247]
i have added a custom template.

.....

```
<ion-item ng-if="viewModel.isArray(viewModel.selectedItems)" ng-repeat="selectedItem in viewModel.selectedItems track by $index" class="item-icon-left item-icon-right item-text-wrap">
         <i class="icon ion-checkmark"></i>
         {{viewModel.getItemValue(selectedItem, viewModel.itemViewValueKey)}}
         <input type="text" name="qty"  placeholder="Enter Qty" />
         <input type="text" name="unit"  placeholder="Enter Units" />
         <i class="icon ion-trash-a" style="cursor:pointer" ng-click="viewModel.removeItem($index)"></i>
      </ion-item>
      <ion-item ng-if="!viewModel.isArray(viewModel.selectedItems)" class="item-icon-left item-icon-right item-text-wrap">
         <i class="icon ion-checkmark"></i>
         {{viewModel.getItemValue(viewModel.selectedItems, viewModel.itemViewValueKey)}}
         <input type="text" name="qty"  placeholder="Enter Qty" />
         <input type="text" name="unit"  placeholder="Enter Units" />
         <i class="icon ion-trash-a" style="cursor:pointer" ng-click="viewModel.removeItem(0)"></i>
      </ion-item>
```
...
how to save view name,qty,unit into separate.
present only names are comma separated.
i need like this 'test1,1,grams', 'test2,4 ,ltrs'.
can you help me on this?

**Comment by guylabs** [comment]
Hi @sivajik34 

what is your exact use case? As this component is an autocomplete component to select single or multiple values coming from a data source. What I see in your custom template is that you want the user to also add some input but that is not supported right now. You are able to fork it and implement that logic but currently that just does not work, as we set the result of the selection as value of the one and only input field which is bound to the component.

Thanks and regards,

Guy

**Comment by sivajik34** [comment]
use case :
for example, a user searching for products.
once they identified item they will select that item and they can request how many quantities, also they can add units.
user can select multiple items.

so I will send this whole list of items to admin as a quote.

**Comment by sivajik34** [comment]
@guylabs may I know where exactly you are comma separated all values into 1 value?

**Comment by guylabs** [comment]
Ok but then you need to add the quantity and units input fields to the main form and use the autocomplete component to only select the product. In the main form you would then need to have some kind of logic that lets you add more products each with an autocomplete input and one for the quantity and units.

This is done here: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L478

**Comment by sivajik34** [comment]
Yes,its good idea.thank you.
