### ISSUE TITLE
Done button appear, but invisible

### ISSUE THREAD

**Issue by saphiree** [guylabs/ion-autocomplete#248]
Hi, before I'm using a template, the done button appeared (sorry, I can't give you the screenshot) .. But after I'm using a template, the done button appears but invisible (it works, but invisible)  .. I tried to look CSS file, but I still can't solve that .. How to make done button not invisible? Thank you :)

This is what I mean, done button appear but invisible
![b612_20180427_074535_067](https://user-images.githubusercontent.com/26443406/39338885-f0512cf0-49ef-11e8-800a-6515a67ae84d.jpg)

This is after I clicked invisible done button
![b612_20180427_074550_092](https://user-images.githubusercontent.com/26443406/39338897-0498b37c-49f0-11e8-9eb0-257430ecb529.jpg)

**Comment by saphiree** [comment]
I tried to copy your master file ion-autocomplete.js .. the placeholder was visible, but still, the DONE button wasn't visible ..

**Comment by guylabs** [comment]
Hi @saphiree 

Could you please try to create a reproducible example of your issue? Please follow the https://github.com/guylabs/ion-autocomplete#guidelines-to-report-an-issue guidelines.

Thanks and regards,

Guy

**Comment by saphiree** [comment]
sorry for the late response, I've just solved that by changing in the CSS file ^^
