### ISSUE TITLE
Cannot pass in pre-populated model

### ISSUE THREAD

**Issue by sclearion** [guylabs/ion-autocomplete#25]
Creating a post with the my new tagging input works fine but when passing in a pre-populated $scope.model, like when updating a post, the tag input shows the comma-separated tag correctly. However when you click to add more tags, the pre-set tags do not appear in the "selected items" modal list. I'm using sample hard-coded data to make sure the data is consistent but still getting same result. using latest build

**UPDATE** I noticed that after selecting tags, the tag object from component has an added **$$hashKey** parameter that I am not saving or passing back in. could this be the reason the component is not picking up my preset tags

```javascript

// works fine when creating posts
$scope.post.tags = [];

// after tags are selected using the matches from callbackMethod(query), 
// the new model looks like this now. perfect! This gets saved to mongo via api and
// the new tags in the 'selected items' modal list show correctly too
$scope.post.tags = [{
    //$$hashKey: "123", im not saving this though??
    id: "126",
    name: "seagate 40726",
    user_id: "1"
},{
    //$$hashKey: "124", im not saving this though??
    id: "125",
    name: "seagate a78",
    user_id: "2"
}];

// when updating the post, passing back in the same data without $$hashKey
// does not display the tags in the 'selected items' modal list, but IT DOES show the 
// csv value in the directive form input correctly
$scope.post.tags = [{
    id: "126",
    name: "seagate 40726",
    user_id: "1"
},{
    id: "125",
    name: "seagate a78",
    user_id: "2"
}];
```

**Comment by guylabs** [comment]
Hi,

I'll have a look at the issue this week and come back to you. I never tested it with a pre populated model.

Thanks for finding the issue.

Regards,

Guy

**Comment by sclearion** [comment]
Awesome thank you for this component. There is nothing else out there that does the job like this one for the ionic platform

**Comment by guylabs** [comment]
Hi,

I finally had the time to work on this issue. Can you please have a look at the [model-to-item-method](https://github.com/guylabs/ion-autocomplete#the-model-to-item-method) documentation and use it in your app and test it with the latest master changes? Can you also provide feedback if it worked then I can close the issue.

Thanks and regards,

Guy

**Comment by sclearion** [comment]
Sorry for the delay, been in a troublesome sprint this week. I will try it out tonight. Thank you

**Comment by guylabs** [comment]
Hi, 

any news on this?

Thanks and regards,

Guy

**Comment by sclearion** [comment]
It works fine sir. Thanks you
