### ISSUE TITLE
Item list from variable won't show first time you start typing

### ISSUE THREAD

**Issue by ChrisAelbrecht** [guylabs/ion-autocomplete#30]
Luv this directive, but I'm experiencing an issue.

When the items-method needs to return an item list stored in a variable, the autocomplete directive won't show any suggestions first time you start typing. You need to delete the text again from the search box and only when typing (from scratch) the 2nd time items load.

See http://codepen.io/ChrisAelbrecht/pen/waewMr for reproducing the issue.

Same codepen here, but with variable directly in items-method: http://codepen.io/ChrisAelbrecht/pen/rVwBxP

I'm using ionic 1.0.0 uranium-unicorn.

Thx,
Chris

**Comment by guylabs** [comment]
Hi Chris,

I just had a look at it and I fixed the issue. Seems to be related to the `collection-repeat` component that its not redrawn correctly, but now it should work. Could you maybe test the latest master and give me feedback such that I can close the issue?

Thanks and regards,

Guy

**Comment by ChrisAelbrecht** [comment]
Hi Guy,

I confirm that it works now. List shows immediatly when you start typing.

Thx for the quick fix!

Chris
