### ISSUE TITLE
Jquery touch event: Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ChrisAelbrecht** [guylabs/ion-autocomplete#31]
When the searchbox appears I get `Uncaught TypeError: Cannot read property '0' of undefined`.

e.touches in onTouchStart seems empty. When debugging I see that they are effectively empty (using Chrome). The event however has `originalEvent` that contains the touches. Changing to that makes it work, but I'm not sure if this has any other side effects.

```javascript
var onTouchStart = function(e) {
     scrolling.moved = false;
     scrolling.startX = e.originalEvent.touches[0].clientX;
     scrolling.startY = e.originalEvent.touches[0].clientY;
};
```

**Comment by guylabs** [comment]
Hi Chris,

do you also get this error in this file here: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html? I do not get it. Can you maybe elaborate more on how you get this issue? When I am able to reproduce it then I can think of a solution.

Thanks for catching it and the workaround!

Regards,

Guy

**Comment by ChrisAelbrecht** [comment]
I founc it's a Chrome related issue. I get the issue in Chrome when activating mobile emulation and more specifically emulating touch screen. See attached screenshot. When I deactivate touch screen emulation the error is not thrown.
FYI, the error doesn't break the javascript.
![error](https://cloud.githubusercontent.com/assets/336027/8093071/e2e90a24-0fbe-11e5-88e6-3f3391cb611e.png)

**Comment by guylabs** [comment]
Hi Chris,

ok then shall we close the issue as explained? 

Thanks and regards,

Guy
