### ISSUE TITLE
JS error when using with jQuery

### ISSUE THREAD

**Issue by trongrg** [guylabs/ion-autocomplete#34]
Hi,

I'm getting this error when using ion-autocomplete with jQuery: Uncaught TypeError: Cannot read property '0' of undefined

This line causes it: https://github.com/guylabs/ion-autocomplete/commit/6105027efff074a48423f8613e9e14838fe09fb3#diff-a7a7d5212fe737f747c11308b339d7acR194

when jQuery is loaded, touch event is different, e.touches is undefined

**Comment by guylabs** [comment]
Hi Trong,

there was already a similar issue which just happened in chrome: #31. Thanks for reporting it!

Regards,

Guy

**Comment by trongrg** [comment]
Yes, #31 is the same issue with this,

However, it does not just happen on Chrome emulator. It always happens on any device with touch event, and jQuery loaded.

The error doesn't break the javascript. It doesn't prevent the autocomplete modal from opening, but it defeats the fix #11
