### ISSUE TITLE
Items removed method

### ISSUE THREAD

**Issue by FabioAntunes** [guylabs/ion-autocomplete#36]
I noticed that the latest stable version doesn't have the [items-removed-method] (https://github.com/guylabs/ion-autocomplete/tree/master#the-items-removed-method)

It's safe to use the Master Branch?

**Comment by guylabs** [comment]
Hi Fabio,

yes its safe as all is tested and the tests are passing. And if there is an issue then it would have also been in a release ;). I hope I am able to release a new version next week.

Thanks and regards,

Guy

**Comment by FabioAntunes** [comment]
Cool! Thanks for the quick response and keep up the good work. Really cool project!

**Comment by guylabs** [comment]
Thanks for the praise :smiley:
