### ISSUE TITLE
How to add item to selected list manually

### ISSUE THREAD

**Issue by DharmendraVaishnav91** [guylabs/ion-autocomplete#37]
I want to add array to item to selectedItems manullay, is there any way to do this.

**Comment by guylabs** [comment]
Hi Dharmendra,

currently this is not supported. But I could add the `selectedItems` as a attribute to the directive which is then always updated with the items that are selected and you would be able to edit this list.

Would that be a possible solution for you?

Thanks and regards,

Guy

**Comment by DharmendraVaishnav91** [comment]
Yes this will solve my issue. When this attribute would be available.

**Comment by guylabs** [comment]
Ok then I will try to add this for the 0.2.3 release.

**Comment by guylabs** [comment]
Hi,

this is already implemented. You just need to have a look at the https://github.com/guylabs/ion-autocomplete#the-model-to-item-method function which you need to implement such that the pre populated model is properly shown.

There were already the following issue: #25, #40.

I think that should solve your issue. If not please reopen it.

Thanks and regards,

Guy
