### ISSUE TITLE
Feature Request: ability to pass in arbitrary data to pass to the template

### ISSUE THREAD

**Issue by taybin** [guylabs/ion-autocomplete#39]
For example, I have created a custom template that I want to reuse in a couple of contexts, but it will have a different title in each place.  It would be great if I could pass in something that would then be available for the template to display.

**Comment by guylabs** [comment]
Hi Taybin,

ok I see. You can have a look at the template here: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomple.js#L64 and checkout the placeholders which get replaced in this template and these you are able to pass into the component. There is no possibility to add more placeholders but I think for the title etc. this should work. Does that work out for you?

Thanks and regards,

Guy

**Comment by taybin** [comment]
I can do that.  It just seemed a little hacky to use cancelLabel for the header title.

**Comment by guylabs** [comment]
Hi Taybin,

I just added the `templateData` attribute with which you are able to pass in arbitrary data to the custom template. Please have a look at the documentation: https://github.com/guylabs/ion-autocomplete#template-data. Can you please tell me if that works out for you such that I can close the issue?

Thanks and regards,

Guy

**Comment by taybin** [comment]
You are on fire with these enhancement requests.  I'll give it a spin and let you know.

**Comment by guylabs** [comment]
hehe ;) thanks.

**Comment by taybin** [comment]
Yes, this is working.  I like that I can even pass in functions too.

**Comment by guylabs** [comment]
Yes exactly i left it completely open of what to pass into the new template. Thanks for the test then I will close that issue.
