### ISSUE TITLE
How to reset ?

### ISSUE THREAD

**Issue by boltex** [guylabs/ion-autocomplete#4]
Is there a way to "clear" or "reset" the autocomplete control?

**Comment by boltex** [comment]
found out how: just clear it's ng-model. 

if it was setup with **ng-model="chosenEquipment.value"**

then do those to reset : 
       **$scope.chosenEquipment = {};**
       **$scope.chosenEquipment.value = null;**

**Comment by guylabs** [comment]
Hi Felix,

do you need to be able to clear/reset the values within the component itself too? I could also add a reset button next to the cancel button which then resets the value.

Thanks and regards,

Guy
