### ISSUE TITLE
set an initial value for the autocomplete and display the initial value when search

### ISSUE THREAD

**Issue by bdairy** [guylabs/ion-autocomplete#40]
HI,
When using the multi select , when I set the ng-model to an already filled array, we see these items comma separated in the input field, but when I search to add new items this list is not displayed. is that a missing feature, a bug, or I am missing something?

**Comment by guylabs** [comment]
Hi,

I will check that and come back to you asap.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

this is already implemented. You just need to have a look at the https://github.com/guylabs/ion-autocomplete#the-model-to-item-method function which you need to implement such that the pre populated model is properly shown.

I think that should solve your issue. If not please reopen it.

Thanks and regards,

Guy
