### ISSUE TITLE
Autocomplete box should open on <tab> as well as click

### ISSUE THREAD

**Issue by TimoSolo** [guylabs/ion-autocomplete#43]
Currently the autocomplete only opens on a click. It should open when receiving focus (eg if tabbing through form fields, or using ios' > "next form element" button)

**Comment by guylabs** [comment]
Hi Timothy,

I just added he `focus` event. Could you maybe test that such that I can release 0.2.3 tomorrow?

Thanks and regards,

Guy

**Comment by TimoSolo** [comment]
Working nicely! thanks
