### ISSUE TITLE
TypeError: Cannot read property '0' of undefined at line 215

### ISSUE THREAD

**Issue by prisonier** [guylabs/ion-autocomplete#44]
Hi,

I'm using ion-autocomplete with ionic 1.0.1 and I get this error in my console.

But it does not break the directive.

**Comment by guylabs** [comment]
Hi,

the directive is not tested on 1.0.1 now. I will check that when I upgrade to the latest version. Thanks for mentioning it!

Regards,

Guy

**Comment by prisonier** [comment]
I also tried with 1.0.0 rc3 and I still have the same problem

**Comment by prisonier** [comment]
YES ! The issue was because I wwas using 0.2.2 instead of 0.2.3. There is no more error even with ionic 1.0.1 so I think you could remove the bug tag and the 0.2.4 milestone. 

When did you release 0.2.3 ? I opened the issue the day I installed ion-autocomplete with bower so it is strange that I installed the 0.2.2. 

Anyway, everything works now.

**Comment by guylabs** [comment]
Hi,

ok nice that it works now. :) I released it last Friday.

Thanks and regards,

Guy

**Comment by prisonier** [comment]
Ok so that's normal that I downloaded 0.2.2.
