### ISSUE TITLE
Autocomplete does not display results of the first request

### ISSUE THREAD

**Issue by prisonier** [guylabs/ion-autocomplete#45]
Hi,

When my "items-method" promise is called for the first time, items are [not displayed](http://hpics.li/1d61f46)

But the following requests [are displayed](http://hpics.li/5475104)

I'm sure that my promise is resolved with an array of items during the first call.

I have tried to init the autocomplete with the ng-model but it did not work so I don't really unsderstand what the ng-model is for.

``` javascript
$scope.autosuggested_stars = []
```

``` html
<label class="item item-input">
  <ion-autocomplete placeholder="Search by star name" items-method="search_by_name(query)" item-view-value-key="display_name" ng-model="autosuggested_stars" item-value-key="id" items-clicked-method="view_star_from_autosuggest(callback)"/>
</label>
```

Don't hesitate to ask me more details.

**Comment by guylabs** [comment]
Hi,

can you maybe try to reproduce it with the following template such that I can reproduce it: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html. You can also create a CodePen if you want with the template here: https://github.com/guylabs/ion-autocomplete#demo

Well you are able to initialize the `ng-model` but then you need to implement the following method: https://github.com/guylabs/ion-autocomplete#the-model-to-item-method

Hope this helps.

Thanks and regards,

Guy

**Comment by prisonier** [comment]
Thanks for the reply, I can't do it right now as I have to go until monday but I think think I do more that populate the autocomplete with a promise. Maybe the problem come from the setTimeout ?

I'm sorry to give you this piece of code without the template you gave me but I must leave right now and just had the time to adapt my function. If you try this code, it should do what I said in my first message.

```html
<ion-autocomplete placeholder="Search by star name" items-method="search_test(query)" item-view-value-key="display_name" ng-model="autosuggested_stars" item-value-key="id"/>
```

``` javascript
    $scope.search_test = function(query){
        return new Promise(function (resolve_1, reject) {

            // Store the search to compare it after a second
            $scope.current_query = query

            // We don't lunch a search if the name.length < 3
            if (query.length >= 3) {

                // Will wait for 1 second before lunch a search
                setTimeout(function () {

                    // If the input has changed, we don't lunch the search
                    if (query === $scope.current_query) {
                        
                        new Promise(function(resolve_2, reject){
                            resolve_2([
                                {
                                    id: 1,
                                    display_name: 'test1'
                                },{
                                    id: 2,
                                    display_name: 'test2'
                                }
                            ])    
                        }).then(function(array_of_items){
                                
                                // Do something on the data

                                resolve_1(array_of_items)
                                
                            })
                    }
                }, 1000)
            }
        })
    }
```

**Comment by guylabs** [comment]
Well this looks very complicated what you want to achieve and for me this has the "premature optimization is the root of all evil" smell in it. Why do you wait 1 second before doing the search? And why do you check if the passed in query is the same than before one second? Just to not call the back end too much?

Some general remarks: Please use the [`$timeout`](https://docs.angularjs.org/api/ng/service/$timeout) service from Angular and the [`$q`](https://docs.angularjs.org/api/ng/service/$q) for creating promises.

And also have a look here on how I test the promise support for the `ion-autocomplete` component:
https://github.com/guylabs/ion-autocomplete/blob/master/test/ion-autocomplete.single-select.spec.js#L226

Hope that helps and I think when you use the `$q` service and remove the complexity of the premature optimization then this will work as till now I never heard of this issue before.

If you need more help on that just ask me.

Thanks and regards,

Guy

**Comment by prisonier** [comment]
I don't see the interest to call the backend for every character typed in the search form. I wait to cancel the request if the search has changed.

I changed setTimeout with $timeout and native Promise with $q but I still have the same result. 

Finally I removed the timeout and the minLength for the search and I still have the same result.

Even if this may be a premature optimization, there is no reason for you plugin to not support it as it is nothing more than a promise.

With this code, I still have an empty result when I type "t".

``` javascript
    $scope.search_test = function (query) {
        return $q(function (resolve_1, reject) {

            $q(function (resolve_2, reject) {
                resolve_2([
                    {
                        id: 1,
                        display_name: 'test1'
                    }, {
                        id: 2,
                        display_name: 'test2'
                    }
                ])
            }).then(function (array_of_items) {

                // Do something on the data
                resolve_1(array_of_items)

            })
        })
    }
```

**Comment by prisonier** [comment]
I tried with only one promise and with 1.0.0 rc3 and still have the same result. I think that I should do something wrong or you would already have spotted this issue.

**Comment by guylabs** [comment]
Hi,

ok nice that it now works. If you want to be on the latest master you can always follow my blog post here: http://guylabs.ch/2015/05/08/get-latest-master-changes-of-a-bower-dependency. This way you always have the latest fixes etc.

Thanks and regards,

Guy
