### ISSUE TITLE
items-clicked-method is called at directive initialisation

### ISSUE THREAD

**Issue by prisonier** [guylabs/ion-autocomplete#46]
Hello,

Just to be sure that it is a wanted behaviour because we have to chack if callback.item is defined in the function given to items-clicked-method.

Regards

**Comment by guylabs** [comment]
Hi,

this issue relates to the #38 issue and the #42 pull request. Please have a look at these issues and I will update this one when I decided how to do it.

Thanks and regards,

Guy

**Comment by TimoSolo** [comment]
Thanks Guy! Keep up the good work - greatly appreciated

**Comment by guylabs** [comment]
Hi,

is this issue still valid? I just fixed a similar issue here #57. I will close this now and if there is still something please reopen it.

Thanks and regards,

Guy
