### ISSUE TITLE
Edit result after selection

### ISSUE THREAD

**Issue by thim81** [guylabs/ion-autocomplete#48]
Hi Guy,

A question about the functionality.

Is it possible to modify the result after I have selected a value?

Scenario:
1) empty ion-autocomplete 
2) Click on it opens the overlay with the search input, cancel button and result list >> start typing "New Y"
3) Select a item >> select a address "New york avenue, NYC, USA" 
4) ion-autocomplete is filled with description value >> New york avenue, NYC, USA

This is all normal behaviour, but now comes the step which the question is about:

5) I want to add a street number to the address, so I click on it, but then step 2 is triggered instead of input keyboard to modify the address. >> desired result: keyboard and modify to "New york avenue 55, NYC, USA "

**Comment by guylabs** [comment]
Hi,

well what I could implement is a button with a magnifier icon which then opens the popup and then you are able to modify the input field. Would that be a solution for you?

Thanks and regards,

Guy

**Comment by marcosafmartins** [comment]
Hi! Can I filter the ion-autocomplete? 
like this code:

    <input type="search" placeholder="Search here" ng-model="users">
    <ion-list>
        <ion-item collection-repeat="item in arrayPais | filter: users" >
            {{item.nome}}
        </ion-checkbox>

**Comment by guylabs** [comment]
@marcosafmartins Please use the #53 issue for the question you have. Thanks.

**Comment by guylabs** [comment]
Hi,

I finnaly had the time after the Ionic 1.1.0 and Angular 1.4.3 upgrade to work on this issue. Can you please check the new `manage-externally` attribute (https://github.com/guylabs/ion-autocomplete#manage-externally) on the master and tell me if this works for you?

You will need to create your own button somewhere and open the search dialog. But this way you can use it to modify the input after the user selected an item.

Thanks and regards,

Guy

**Comment by thim81** [comment]
This looks great. I m going to implement and test it. Thanks Guy!

**Comment by guylabs** [comment]
Hi,

any news on this? I want to release 0.3.1 asap such that all can update to a proper version. ;)

Thanks and regards,

Guy

**Comment by thim81** [comment]
Hi Guy,

Currently stuck with fixing some strange bugs after the update to ionic 1.1.0. 

Hope to find some time next week. 

Regards,
Tim

**Comment by huskywhale** [comment]
Inorder to filter just change the line 95 of ion-autocomplete.js from

ion-item collection-repeat="item in viewModel.searchItems " item-height="55px" item-width="100%" ng-click="viewModel.selectItem(item)"
to

ion-item collection-repeat="item in viewModel.searchItems |filter: viewModel.searchQuery " item-height="55px" item-width="100%" ng-click="viewModel.selectItem(item)"
Add the term filter: viewModel.searchQuery. this will filter the search result.

Thanks a lot for this plugin guylabs!

**Comment by guylabs** [comment]
Hi Tim,

any news on this? I am sorry to always ask you but I need to release `0.3.1` soon such that I can finish off some issues.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
I will close the issue as there is no feedback anymore. If it still is an issue please reopen it.

Thanks and regards,

Guy

**Comment by thim81** [comment]
Hi Guy,

Sorry again for my late response. I've planned to implement the "master" today and provide any feedback. 

I have not upgraded ionic to the newest version due to Angular update issues, so I'll let you know how it turns out and thanks for the patience.

Regards,
Tim
