### ISSUE TITLE
Validation classes such as ng-pristine, ng-dirty, etc...

### ISSUE THREAD

**Issue by boltex** [guylabs/ion-autocomplete#5]
Thanks for this nice autocomplete control for ionic.

Are there ways to use those classes (ng-pristine, ng-dirty, etc...) to do some validation with this control?

**Comment by guylabs** [comment]
Hi Felix,

thanks for this good question: I think I need to change the directive restriction to `C` such that you can define the input field with the `ion-autocomplete` CSS class and use your `ng-pristine`, `ng-dirty` classes as well. What do you think about that ? 

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Felix,

now you are able to use the `ion-autocomplete` with the element and the attribute restriction such that you are able to have your own input field with your validations and then just add the `ion-autocomplete` attribute. Can you maybe test your use case if you have the time before I do the release?

You can see the examples on how to use it here: https://github.com/guylabs/ion-autocomplete#usage

Thanks and regards,

Guy
