### ISSUE TITLE
Search popup is never removed from DOM

### ISSUE THREAD

**Issue by ArTiSTiX** [guylabs/ion-autocomplete#50]
I use many Search inputs, in different views.
I didn't found any way in current version to set which modal should be open (if you could add an option to reuse modals to have multiple inputs, it would be awesome, ...maybe wrong).

But when the view containing the input is destroyed, the ion-autocomplete modal is never removed from DOM. After some time using my application, i have plenty of modals in DOM.

**Comment by guylabs** [comment]
Hi Rémi,

thanks for reporting this issue! I will have a look at it as soon as I have the time. If you need it urgently then maybe a pull request from your side would be really appreciated ;) as currently I do not have that much time, and there are some other issues I need to check first.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Rémi,

after the upgrade to Ionic 1.1.0 and Angular 1.4.3 and the change to the `bindToController` I realized that  we need to use a modal per autocomplete component, as if not, the model bindings don't work properly and we just compile the template once. But I added a fix to it that multiple modals can be opened.

What do you mean with the view is destroyed? Ionic caches them and therefore you have all the elements in the DOM somehow. Can you maybe elaborate more on this? If there is a callback then we could remove it from the DOM.

I will close this now as I cannot fix it.

Thanks and regards,

Guy
