### ISSUE TITLE
How to use my own view for displaying results.

### ISSUE THREAD

**Issue by 5amfung** [guylabs/ion-autocomplete#52]
It seems when I click on the input, a different view is popped up.  But what if I want to use my own view for displaying the results.  I don't seem to find the option to turn it off.

Thanks in advance.

**Comment by guylabs** [comment]
Hi Sam,

what do you mean by different view? You mean the view where the search input field is and where the results of the query are shown?

Thanks and regards,

Guy

**Comment by 5amfung** [comment]
Right.

**Comment by guylabs** [comment]
Well you are able to change the template of what is displayed inside this dialog with the `template-url` parameter: https://github.com/guylabs/ion-autocomplete#template-url

With this you are able to define your own view. Have a look here how the default template looks like: https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L70

Hope this helps.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Sam,

any news on this?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Sam,

I will close the issue now. If you have any news on this please reopen it.

Thanks and regards,

Guy
