### ISSUE TITLE
how use ion-autocomplete ?

### ISSUE THREAD

**Issue by scorpioRED** [guylabs/ion-autocomplete#53]
Please somebody help me with ionic autocomplete.
I have 2 questions :

I have array,it`s look like

 array = [
{name:'some name' , id:'01'},
{name:'some name' , id:'02'},
{name:'some name' , id:'03'}]
how i can use ionic autocomplete to search I'm my array?

2) This array has more than 3000 items.How fast will be work autocomplete with this large array?

**Comment by guylabs** [comment]
Hi,

you can have a look at the online demo here: https://github.com/guylabs/ion-autocomplete#demo and then change the return value of the `getTestItems` method to your array. Then you need to change the `item-value-key` to `id` such that id gets stored in the model and the `item-view-value-key` to `name` such that the name is displayed in the autocomplete list.

You can also have a look at these examples here: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html

For your second question: The list is done with the Ionic collection repeat and this should be performant also with a high amount of items. But you need to test it by yourself as I do not have any performance tests.

I hope this helps you. And if you have any other questions please check the documentation first as there everything is written about the component.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

I will close the issue now. If you have any questions on this please reopen it.

Thanks and regards,

Guy

**Comment by marcosafmartins** [comment]
Hi! Can I filter ht <ion-autocomplete>? like this:

        <input type="search" placeholder="Search here" ng-model="users">
        <ion-list>
            <ion-item collection-repeat="item in arrayPais | filter: users" >
                {{item.nome}}
            </ion-checkbox>

**Comment by guylabs** [comment]
Hi Marco,

there is no such functionality, but you can use an own template and add the filtering as you need it. Check the following page on how to do it: https://github.com/guylabs/ion-autocomplete#template-url

Thanks and regards,

Guy

**Comment by huskywhale** [comment]
Inorder to filter just change the line 95 of ion-autocomplete.js from 
> ion-item collection-repeat="item in viewModel.searchItems  " item-height="55px" item-width="100%" ng-click="viewModel.selectItem(item)"
                    
to  
> ion-item collection-repeat="item in viewModel.searchItems |filter: viewModel.searchQuery " item-height="55px" item-width="100%" ng-click="viewModel.selectItem(item)"

Add the term filter: viewModel.searchQuery. this will filter  the search result.

Thanks a lot for this plugin guylabs!

**Comment by turaku** [comment]
Hi 

I have problem where using ion autocomplete from http using database. I also used Angular Service, when doing query or search, Unfortunatly All items are shown from database. I expected each character is filtering the query.

`<input name="customer_id"
                      ion-autocomplete type="text"
                       readonly="readonly"
                       class="ion-autocomplete"
                       autocomplete="off"
                       ng-model="add.customer_id"
                       item-value-key="id"
                       item-view-value-key="name"
                       items-method="callbackMethod(query, isInitializing)"
                        items-clicked-method="itemsClicked(callback)"
                        cancel-button-clicked-method="itemsRemoved(callback)"
                       max-selected-items="1" required>`


`$scope.model = "";
    $scope.clickedValueModel = "";
    $scope.removedValueModel = "";
    $scope.callbackMethod = function (query, isInitializing) {
      if (query) {
        return customerService.getData(query);
      }
      return {};
    };
    $scope.itemsClicked = function (callback) {
      $scope.clickedValueModel = callback;
    };
    $scope.itemsRemoved = function (callback) {
      $scope.removedValueModel = callback;
    };`

Would you please tell me why?

Thank you and Regards
