### ISSUE TITLE
How to use the "model-to-item-method"

### ISSUE THREAD

**Issue by Vahn84** [guylabs/ion-autocomplete#54]
Hi

first of all thanks for this "plugin".  

What i need to understand is how to prepopulate the model that i'm using for the autocomplete,

I get from the server an array of tags, I push it into my model and the tags appear as text inside the input field of the ion autocomplete object. 

But when i click on it to find or remove tags, the prepopulated model seems empty, because it doesn't list (as selected) any of the tags that it shows in the input field.

So i found this function ""model-to-item-method" but i cannot make it work. Would you mind showing a full and working example?

Thanks

**Comment by Vahn84** [comment]
I forgot to mention that everything else works like a charm, all is ok: querying new items, selecting them ...all works properly. Everything but the prepopulation of the model...

**Comment by guylabs** [comment]
Hi,

thanks for the praise :). Ok I do have an automated end to end test for this which runs as expected. Can you maybe try to reproduce your issue with this template here: https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.prepopulated.e2e.html ? This is the one I use for the end to end test and this works when you try it.

If you cannot get it to run, can you then please create a snippet on codepen based on the demo inside the documentation, such that I can check it where the problem is.

I hope this helps you.

Thanks and regards,

Guy

**Comment by Vahn84** [comment]
Ty mate!

i will give it a try tomorrow. I'll let you know if everything is OK. 

Thanks

Fabio

**Comment by Vahn84** [comment]
Hi mate

i've followed you're suggestion and you're example but with no luck

this is my autocomplete directive

<ion-autocomplete ng-model="citta.comune" item-view-value-key="comune" items-method-value-key="result" items-method="callbackMethod(query)" items-clicked-method="clickedMethod(callback)" model-to-item-method="getItemFromModelValue(modelValue)"/>

and this is my model to item method

//METHOD FOR PREPOPULATING CITY
	$scope.getItemFromModelValue = function (modelValue) {
		console.log("mtim");
                        return {
                                                        cap: modelValue,
							codice_comune: modelValue,
							comune: modelValue,
							id: modelValue,
							id_provincia: modelValue,
							regione:modelValue,
							sigla_provincia: modelValue
                        }
                    };


what i'm doing wrong?

**Comment by Vahn84** [comment]
it works mate!

**Comment by guylabs** [comment]
Ok nice! :). What was the problem?

**Comment by Vahn84** [comment]
A problem with my object! Thanks again for your work, this is a very useful piece of code!

**Comment by guylabs** [comment]
Ok. Thanks a lot Fabio!

**Comment by bebud** [comment]
Hi Guy. Great work! 
Is it possible to pre populate the list without having to set multi select to true (for single item selection)? 
I took your e2e example and set one item in the model and multi select to false. The list is now empty but modelvalue is set.
http://codepen.io/bebud/pen/Pqxzpj

**Comment by guylabs** [comment]
Hi Behboud,

I will tackle this usecase in this issue #58, such that you are also able to prepopulate single items.

Would that be a solution for you?

Thanks and regards,

Guy

**Comment by behboud** [comment]
@guylabs sure. Appriciate your help.
