### ISSUE TITLE
Clear Selected Item

### ISSUE THREAD

**Issue by aelx311** [guylabs/ion-autocomplete#58]
Hello, how do I clear the input value after selecting one item (NOT multiple-select)? Clicking 'Cancel' will only dismiss the modal.

**Comment by guylabs** [comment]
Hi Alex,

this is currently not possible. Maybe I will use the multiple select functionality and add something like a max/min selected attribute such that you are able to define how much elements can be selected. And then you are able to delete the selected values.

Would that be a solution for you?

Thanks and regards,

Guy

**Comment by aelx311** [comment]
Hi Guy,

Yes. That is what I am doing now. I think that would be great as a default behavior in single select mode.

Thanks for your quick respond!

**Comment by guylabs** [comment]
Hi Alex,

could you maybe test the new `max-selected-items` attribute on the master? I just added the functionality here: https://github.com/guylabs/ion-autocomplete/commit/a0d5a16ee3a1e233c3457e395785afb1e0512ddf. Please also read the new documentation: https://github.com/guylabs/ion-autocomplete#the-max-selected-items as there everything is written how to use this.

Can you give me feedback such that I then can close the issue?

Thanks and regards,

Guy

**Comment by aelx311** [comment]
Hello,

Yes! The max-selected-items is working. Thank you for the enhancement.

I would like to suggest another enhancement, that is it would be nice to replace the selected item when max-selected-items is 1.

**Comment by guylabs** [comment]
Hi Alex,

ok I see. I just fixed this issue. Thanks for reporting it! I will close the issue now as I think everything is ok now. If there is something else, just reopen it.

Thanks and regards,

Guy

**Comment by amilino** [comment]
@guylabs How do I **NOT** clear the input value after selecting one item (**WITH** multiple-select)? This is very strange behavior, to lose input value after selecting one item, because I am in multi-select mode.

Thank you and regards,
Alan

**Comment by guylabs** [comment]
Hi @amilino,

lets discuss this on #178.

Thanks and regards,

Guy
