### ISSUE TITLE
Using bower to install autocomplete

### ISSUE THREAD

**Issue by justinweathersby** [guylabs/ion-autocomplete#59]
Hey guys im pretty new to angular as well as ionic, so take it easy on me. Your autocomplete component looked like a great fit for what i was trying to do with my personal ionic app, but im a little confused as to why the initial bower install command would completely reformat the layout of my angular and ionic libraries. Also I dont have a /bower_components directory so the second installation step of including those files fail and in turn the third step to include the ion-autocomplete fails. So instead I removed the link to the file inside the bower_components dir. and pointed to where the install had saved it.. boom works. But im still just confused as to why the bower install command removed files like my angular ng-resource and reorganized everything else, all without making a bower_components directory. Should I have installed this component differently?

Attached is a screenshot of all the files that where moved or renamed or deleted:
<img width="695" alt="screenshot 2015-08-20 13 41 45" src="https://cloud.githubusercontent.com/assets/5218938/9390866/c5b2df38-4741-11e5-9ec0-06dcdc076e22.png">

**Comment by guylabs** [comment]
Hi Justin,

well the standard Ionic project sets up bower a little bit different. It changes the standard location of the `bower_components` to be in the `www/lib`. For that see the `.bowerrc` file in your project. But when you just execute `bower install ion-autocomplete` you should just have a change in the `www/lib/ion-autocomplete` directory and you need to adapt the path accordingly.

I hope this explanation helps you :).

Thanks and regards,

Guy

**Comment by justinweathersby** [comment]
Thanks I was able to uncommit then change the directive in the .bowerrc file and then after that run the bower install. Everything worked much better, all condensed into its own directory. I have everything setup so that the items are populated from an api request, which works and the correct item is passed along in my post request to the same api. But for some reason the search field does not change the items shown. When the modal first opens, no items are shown. Then once i press any letter, all of the items are shown. If the word foo is an item in the list and I type foo, nothing happens all of the items stay shown. Any idea as to why the search field wouldnt be working for me?

**Comment by guylabs** [comment]
Hi Justin,

you need to implement the search functionality inside the https://github.com/guylabs/ion-autocomplete#the-items-method method. The `ion-autocomplete` component just passes the string from the modal to this method and then this method needs to return the correct items according the search term.

I would first go through the whole documentation and also have a look at the demo at codepen or the samples of the integration tests.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Justin,

any news on this? If yes please reopen the issue.

Thanks and regards,

Guy
