### ISSUE TITLE
Support for returning alternate value from ngModel.$render

### ISSUE THREAD

**Issue by goneale** [guylabs/ion-autocomplete#60]
Hi @guylabs, first of all great angular directive.

I have taken advantage of the templating functionality to display a City and State using State inside an "item-note" span. See screenshot
![image](https://cloud.githubusercontent.com/assets/107109/9432717/89b76fb8-4a6a-11e5-9854-d7b9ca7f9bc1.png)

So far, working great. However, when I then see the returned value on the input field, it is [object Object], which makes sense as you run `element.val(scope.getItemValue(ngModel.$viewValue, scope.itemViewValueKey));` in `ngModel.$render`. See screenshot
![image](https://cloud.githubusercontent.com/assets/107109/9432736/ea6cd53c-4a6a-11e5-9845-8122dfbe156e.png)

Is there any possibility to give an ng attribute to specify what model/property should be returned into element.val()? For example, in this case, I would want a format of `{City}, {State}` to be written into the input box.

Or if you already know of a better way I should be doing this, let me know.

Below is my template and directive setup:
```
<ion-autocomplete ng-model="model.AppointmentAddressCity"
		item-value-key="name"
		item-view-value-key="view"
		items-method="getCityQuery(query)"
		items-method-value-key="items"
		multiple-select="false"
		placeholder="Enter City or Postcode..."
		select-items-label="Select city..."
		items-clicked-method="itemsClicked(callback)"
		template-url="templates/city-select.html" />
```

city-select.html
```
<div class="ion-autocomplete-container modal">
	<div class="bar bar-header item-input-inset">
		<label class="item-input-wrapper">
			<i class="icon ion-search placeholder-icon"></i>
			<input type="search" class="ion-autocomplete-search" ng-model="searchQuery" placeholder="{{placeholder}}" />
		</label>
		<div class="ion-autocomplete-loading-icon" ng-if="showLoadingIcon && loadingIcon">
			<ion-spinner icon="{{loadingIcon}}"></ion-spinner>
		</div>
		<button class="ion-autocomplete-cancel button button-clear">{{cancelLabel}}</button>
	</div>
	<ion-content class="has-header has-header">
		<ion-list>
			<ion-item class="item-divider" ng-show="selectedItems.length > 0">{{selectedItemsLabel}}</ion-item>
			<ion-item ng-repeat="selectedItem in selectedItems track by $index" type="item-text-wrap" class="item-icon-left item-icon-right">
				<i class="icon ion-checkmark"></i> {{getItemValue(selectedItem, itemViewValueKey).City}}
				<span class="item-note">{{getItemValue(selectedItem, itemViewValueKey).State}}</span>
				<i class="icon ion-trash-a" style="cursor:pointer" ng-click="removeItem($index)"></i>
			</ion-item>
			<ion-item class="item-divider" ng-show="items.length > 0">{{selectItemsLabel}}</ion-item>
			<ion-item collection-repeat="item in items" item-height="55" item-width="100%" type="item-text-wrap" ng-click="selectItem(item)">
				{{getItemValue(item, itemViewValueKey).City}}
				<span class="item-note">{{getItemValue(item, itemViewValueKey).State}}</span>
			</ion-item>
		</ion-list>
	</ion-content>
</div>
```

Thanks again

**Comment by goneale** [comment]
Better yet, how about a community contribution :)
https://github.com/guylabs/ion-autocomplete/pull/61

Let me know what you think.
Graham

**Comment by guylabs** [comment]
Hi Graham,

thanks for the praise and for the pull request. I just had a look at it and I will add some comments to it such that we can merge it to the master. Really cool that you want to contribute!

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Graham,

I just had a look at the original implementation and I already use the `$parse` service from Angular. So you are already able to create complex format expressions. You just need to set the https://github.com/guylabs/ion-autocomplete#the-item-view-value-key to something like this and it will work:

```javascript
item-view-value-key="'City + ', ' + State"
```

Then it will show inside the list and in the input field, so you do not need to have the template anymore.

I hope this fixes the issue and then the pull request is not needed anymore. Could you please try it and give me feedback?

Thanks and regards,

Guy

**Comment by goneale** [comment]
Hi Guy,

Thanks for the response. Great if we could get an existing solution working...

I tried,
```
item-view-value-key="'City + ', ' + State"
```
```
item-view-value-key="City + ', ' + State"
```
and
```
item-view-value-key="'City + ', ' + State'"
```

But to no avail, one returning blank and one returning error: `[$parse:lexerr] Lexer Error: Unterminated quote at columns 21-22 ['] in expression ['City + ', ' + State''].` Any thoughts?

Graham

**Comment by guylabs** [comment]
Hi Graham,

there was a typo in my first expression. The first single quote was wrong, sorry for that. Please have a look at the https://github.com/guylabs/ion-autocomplete/blob/master/test/e2e/ion-autocomplete.single-select.e2e.html and then you can try the following `item-view-value-key`:

```javascript
item-view-value-key="id + ', ' + name"
```
And this works with this template. You need to add the exact property names of your JSON object which is returned from the `items-method`. 

Hope you get it to work and maybe have a look at the documentation of the `$parse` service as there are also examples: https://docs.angularjs.org/api/ng/service/$parse

Regards,

Guy

**Comment by goneale** [comment]
Hi again Guy,

Had some time to spend this afternoon and got it working with the existing version.

This is what eventually worked for me:
```html
<ion-autocomplete ng-model="model.AddressLocationID" item-value-key="ID" item-view-value-key="view.City + ', ' + view.State" items-method="getCityQuery(query)"
	items-method-value-key="items" multiple-select="false" placeholder="" select-items-label="Select city..." 
	template-url="templates/city-select.html" />
```

Note I went through `view.` to get this happening:
```html
<div class="ion-autocomplete-container modal">
	<div class="bar bar-header item-input-inset">
		<label class="item-input-wrapper">
			<i class="icon ion-search placeholder-icon"></i>
			<input type="search" class="ion-autocomplete-search" ng-model="searchQuery" placeholder="Enter City or Postcode..." />
		</label>
		<div class="ion-autocomplete-loading-icon" ng-if="showLoadingIcon && loadingIcon">
			<ion-spinner icon="{{loadingIcon}}"></ion-spinner>
		</div>
		<button class="ion-autocomplete-cancel button button-clear">{{cancelLabel}}</button>
	</div>
	<ion-content class="has-header">
		<ion-list>
			<ion-item class="item-divider" ng-show="selectedItems.length > 0">{{selectedItemsLabel}}</ion-item>
			<ion-item ng-repeat="selectedItem in selectedItems track by $index" type="item-text-wrap" class="item-icon-left item-icon-right">
				<i class="icon ion-checkmark"></i> {{selectedItem.view.City}}
				<span class="item-note">{{selectedItem.view.State}}</span>
				<i class="icon ion-trash-a" style="cursor:pointer" ng-click="removeItem($index)"></i>
			</ion-item>
			<ion-item class="item-divider" ng-show="items.length > 0">{{selectItemsLabel}}</ion-item>
			<ion-item collection-repeat="item in items" item-height="55" item-width="100%" type="item-text-wrap" ng-click="selectItem(item)">
				{{item.view.City}}
				<span class="item-note">{{item.view.State}}</span>
			</ion-item>
		</ion-list>
	</ion-content>
</div>
```

getCityQuery()
```javascript
$scope.getCityQuery = (query) => {
	if (!query)
		return [];
	var deferred = this.$q.defer();
	this.lookupService.getLocations(query) // $http factory call
		.then((results: any) => {
			deferred.resolve(results.map(function(result) {
				return { items: { ID: result.ID, name: result.C, view: { City: result.C, State: result.S } } }
			}));
		});
	return deferred.promise;
```

Perhaps I still have a couple of redundancies, I'm not sure. But after understanding the workflow and the object graph, the whole thing makes a lot more sense now!

It would be great to see examples of complex templates on your GitHub page, feel free to share any of my above approaches :)

Graham

**Comment by guylabs** [comment]
Hi Graham,

nice! Ok but you would not need the special template if it is ok for you to show the items as `City, State`. This way you always need to create a new template for each `ion-autocomplete` component you need in your project.

About the examples: Good idea! Maybe I will add some more codepen demos on how to achieve these things.

Can I then close the issue?

Thanks and regards,

Guy

**Comment by goneale** [comment]
Ah, but I do need the special template to place State into `<span class="item-note">` unless you have a better suggestion?

**Comment by guylabs** [comment]
Well you do not need to show the state in the special template. You can also try to remove it and then see what the result looks like.

**Comment by goneale** [comment]
No it's a business requirement to show the state, I don't just want to show the suburb, and looks a bit nicer in the item-note, rather than just with comma.

**Comment by guylabs** [comment]
Ok then I would also leave it as it is. :) Can I then close the issue?

**Comment by goneale** [comment]
Yep :+1: Thanks a lot.
