### ISSUE TITLE
Refreshing selected items from model

### ISSUE THREAD

**Issue by Diodeus** [guylabs/ion-autocomplete#62]
After the autocompleter has loaded, I'd like to be able to all the user to type in email addresses that are not in the results list, and have them added to the selected items. I do this by adding a timeout on the query and checking to see if the value is a valid email address. Then I call the model-to-item method. I see the new item being added to the model used in the directive, but it never renders.

<ion-autocomplete ng-model="listData"
model-to-item-method="autocompleterViewCntrl.addContact(modelValue)" ......

- - -

AutocompleterView._fetchContacts = function(query) {
$log.log("Autocompleter:searching", _vm.contacts.length);
   var results = {contactResults: $filter('filter')(_vm.contacts, {displayName:query, email:query}, false)};
   var valid = _filter("validEmail")(query);
   clearTimeout(_vm.keyTimer);
   if(valid) {
        _vm.keyTimer = setTimeout(function() {
             $log.log("Adding from manual:", query);
            _cntrl.addContact(query)
        },300)
   }
   return results;
}

AutocompleterView._addContact = function(modelValue) {   
    if(_vm.listData.indexOf(modelValue)>-1) {
        return modelValue;
    }
    _vm.listData.push(modelValue);
   $log.log("Autocompleter:add contact", modelValue, _vm.listData);
   return modelValue;
}

**Comment by guylabs** [comment]
Hi,

the `model-to-item-method` is used to retrieve the item by the model value and this is just used when you prefetch the model with model values. 

The functionality you want is not implemented and it is not that easy to implement because the component separates the model and the view value and the user always sees the view value and not the model value.

But I could add a configuration option with which you are able to edit the main input field where the model is stored such that you are able to override the selected value or define your own.

Would that be a solution for you?

Thanks and regards,

Guy

**Comment by Diodeus** [comment]
I'm not sure. I have ng-model="listData", and internally you use ( model: '=ngModel' ), so it's not really pointing to the one I've defined? I would have expected it to.

So, yes, if I can define doing that as an option, that would be great.

Thank you.

**Comment by guylabs** [comment]
Ok then I will have a look at it in the next milestone, as for this one there are a lot of other issues.

Thanks for showing me this use case.

Regards,

Guy

**Comment by Diodeus** [comment]
Is it possible to make this work through a fake query in the items-method?

**Comment by Diodeus** [comment]
I managed to do exactly that, fire a fake query and add the typed-in email address to the results list and generate a click on that element to add it to the selection list. It's an ugly hack, but does the job.

**Comment by guylabs** [comment]
Ok yes that is an ugly hack but it works for now as you said. I will try to do my best to implement this asap. May you post the code how you did it for a reference for others which have the same issue now and need a quick fix?

**Comment by Diodeus** [comment]
This waits for the user to stop typing. If it detects a valid email address (filter not included here) it will push the manually-entered value into the results list and generate a click to add it to the selection list. It's not perfect, if someone is a slow typing and types "x@@.co" (for example) it will pick it up as a valid email address and will fire again on "x@y.com".

 AutocompleterView._fetchContacts = function(query) {
           var results = {contactResults: $filter('filter')(_vm.contacts, {displayName:query, email:query}, false)};
           var valid = _filter("validEmail")(query);
           clearTimeout(_vm.keyTimer);
           if(valid) {
                $log.log("Adding from manual:", query);
                var tmpData = {displayName:query, email:query};
                results.contactResults.push(tmpData);
                //find the element and click it
                setTimeout(function() {
                    var foundItems = document.getElementsByClassName("result");
                    for(var index in foundItems) {
                        var foundElement = angular.element(foundItems[index])[0];
                        if(!angular.isUndefined(foundElement) && !angular.isUndefined(foundElement.innerText) && foundElement.innerText.indexOf(query)>-1) {
                            angular.element(foundItems[index]).triggerHandler("click");
                        }
                    }
                },800);
           }
           return results;
        }

**Comment by guylabs** [comment]
I just had a look at it again and this cannot be implemented in the directive itself as the directive doesn't know the structure of an item which is retrieved from the backend and this would be too complicated to create. An other easy way would be the new `managed-externally` attribute which I implemented here (https://github.com/guylabs/ion-autocomplete/issues/48#issuecomment-137913312). 

There you could create an editable input field and then have a button which is called "select ..." and there you would select the values from the backend and if they want to provide their own email address they could just enter it into the input field directly. Do you know what I mean?

This way you can do any validation logic on the input field directly and you do not need to create ugly workarounds.

I will close the issue as I think this is not doable as you want it. We can still discuss about the other option.

Hope this helps you.

Thanks and regards,

Guy
