### ISSUE TITLE
I am using the autocompleter inside $ionicModal. The DONE button hides inner elements, not the modal.

### ISSUE THREAD

**Issue by Diodeus** [guylabs/ion-autocomplete#63]
One thing the documentation lacks, is how to implement this within other views. Right now I have this rendered through $ionicModal to give me control of opening and closing the autocompleter. Unfortunately I don't get access to the DONE button event, so I cannot close the modal. The DONE button hides the autocompleter element instead, leaving the modal open, but empty.

How can this be implemented to hide/show from a parent view?

**Comment by guylabs** [comment]
Hi,

so you would need a callback when the `done` button is clicked such that you can also call custom code and close the modal on your side right? Then you would be able to configure a method which is then called.

Would that be a solution for you?

Thanks and regards,

Guy

**Comment by Diodeus** [comment]
I've used a custom template and put the done button in its own controller in order to access it without worrying about the built-in stopPropagation and preventDefault. Thanks.

**Comment by guylabs** [comment]
Ok so you already solved it by using a custom template. But would this callback be a solution for you? If not then we can close the issue, but if yes, then I will try to implement this functionality.

**Comment by guylabs** [comment]
Hi, 

I just added the new `cancel-button-clicked-method` attribute where you are able to provide a callback method. I hope that suits your needs. Please try everything on the master and then come back to me if it worked such that I can close the issue.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

any news on this? I want to release 0.3.1 asap such that all can update to a proper version. ;)

Thanks and regards,

Guy

**Comment by Diodeus** [comment]
Sorry for the delay Guy. A lot of pressure at work with the end of sprint.
I'll grab and give it a try tomorrow.

- James.



On Thu, Sep 17, 2015 at 4:24 PM, Guy Brand <notifications@github.com> wrote:

> Hi,
>
> any news on this? I want to release 0.3.1 asap such that all can update to
> a proper version. ;)
>
> Thanks and regards,
>
> Guy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141217305>
> .
>



-- 
->|-

**Comment by Diodeus** [comment]
I tried master and the control does not render. I get a blank screen when opening it and no console errors. I tried 0.3.0 (was on 0.2.3, which worked) and get the same issue, so I suspect this is related to 0.3.0. Here is how I'm opening it:

ComposeView._initModal = function() {
            var autocompleteTemplate = $ionicModal.fromTemplateUrl("templates/autocompleter.html", {
                scope: _vm,
                backdropClickToClose: false,
                focusFirstInput: true,
                animation: "slide-in-up"
            });
            autocompleteTemplate.then(function(modal) {
                _vm.modal = modal;
                _vm.modal.show();
                $log.log("Compose:Modal created:", _vm.modal);
            });
        };

**Comment by guylabs** [comment]
Which Ionic version are you using? Please have a look at https://github.com/guylabs/ion-autocomplete#ionic-compatibility. So your custom modal doesn't show or the modal of `ion-autocomplete` when clicking on the input?

**Comment by Diodeus** [comment]
Hi Guy, I am using Ionic 1.4.2.

I've turned off the custom template in the autocomplete, made no other code
changes other than to grab master. I can see the autocompleter in the DOM,
but it doesn't seem to be in the viewport. Hmmm... I'll take a look at this
after lunch. If you can think of anything let me know.

Thank you.

- James.

<div class="modal-wrapper" ng-transclude=""><ion-modal-view
class="autocompleter-view modal slide-in-up ng-enter active
ng-enter-active" title="Addresses"
ng-controller="AutocompleterViewController as autocompleterViewCntrl">
    <ion-content scroll="true" class="scroll-content ionic-scroll"><div
class="scroll" style="transform: translate3d(0px, -61.5px, 0px) scale(1);">
<ion-autocomplete ng-model="listData" item-value-key="displayName"
item-view-value-key="email"
items-method="autocompleterViewCntrl.fetchContacts(query)"
items-removed-method="autocompleterViewCntrl.setTokens(callback)"
model-to-item-method="autocompleterViewCntrl.addContact(modelValue)"
items-clicked-method="autocompleterViewCntrl.setTokens(callback)"
items-method-value-key="contactResults" select-items-label="Select an email
address" multiple-select="true" placeholder="TO:  - type email address"
component-id="to" cancel-label="Done" class="ng-pristine ng-untouched
ng-valid">
    </ion-autocomplete></div><div class="scroll-bar scroll-bar-v"><div
class="scroll-bar-indicator" style="transform: translate3d(0px, 0px, 0px)
scaleY(1); height: 0px; transform-origin: center bottom
0px;"></div></div></ion-content>
</ion-modal-view></div>

On Fri, Sep 18, 2015 at 12:16 PM, Guy Brand <notifications@github.com>
wrote:

> Which Ionic version are you using? Please have a look at
> https://github.com/guylabs/ion-autocomplete#ionic-compatibility. So your
> custom modal doesn't show or the modal of ion-autocomplete when clicking
> on the input?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141496805>
> .
>



-- 
->|-

**Comment by guylabs** [comment]
Hmm...what kind of Ionic package do you use? The latest official version of Ionic is `1.1.0` (see https://github.com/driftyco/ionic/releases) and you will need to use this version. And the element tag `ion-autocomplete` is not working anymore you need to use it as attribute as this was removed from `0.3.0` and you can remove the `multiple-select="true"` attribute too. Please also have a look at the release notes: https://github.com/guylabs/ion-autocomplete/blob/master/RELEASENOTES.md

**Comment by Diodeus** [comment]
Actually we're on 1.3.14

On Fri, Sep 18, 2015 at 12:34 PM, Guy Brand <notifications@github.com>
wrote:

> Hmm...what kind of Ionic package do you use? The latest official version
> of Ionic is 1.1.0 (see https://github.com/driftyco/ionic/releases) and
> you will need to use this version. And the element tag ion-autocomplete
> is not working anymore you need to use it as attribute as this was removed
> from 0.3.0 and you can remove the multiple-select="true" attribute too.
> Please also have a look at the release notes:
> https://github.com/guylabs/ion-autocomplete/blob/master/RELEASENOTES.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141501349>
> .
>



-- 
->|-

**Comment by Diodeus** [comment]
Sorry, that was Angular. we're on this:

   "ionic": "driftyco/ionic-bower#1.0.1",

On Fri, Sep 18, 2015 at 12:34 PM, Guy Brand <notifications@github.com>
wrote:

> Hmm...what kind of Ionic package do you use? The latest official version
> of Ionic is 1.1.0 (see https://github.com/driftyco/ionic/releases) and
> you will need to use this version. And the element tag ion-autocomplete
> is not working anymore you need to use it as attribute as this was removed
> from 0.3.0 and you can remove the multiple-select="true" attribute too.
> Please also have a look at the release notes:
> https://github.com/guylabs/ion-autocomplete/blob/master/RELEASENOTES.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141501349>
> .
>



-- 
->|-

**Comment by Diodeus** [comment]
Do you think this is because I'm loading the autocompler into $ionicDialog

On Fri, Sep 18, 2015 at 12:34 PM, Guy Brand <notifications@github.com>
wrote:

> Hmm...what kind of Ionic package do you use? The latest official version
> of Ionic is 1.1.0 (see https://github.com/driftyco/ionic/releases) and
> you will need to use this version. And the element tag ion-autocomplete
> is not working anymore you need to use it as attribute as this was removed
> from 0.3.0 and you can remove the multiple-select="true" attribute too.
> Please also have a look at the release notes:
> https://github.com/guylabs/ion-autocomplete/blob/master/RELEASENOTES.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141501349>
> .
>



-- 
->|-

**Comment by Diodeus** [comment]
From what it looks like, the ion-autocomplete is in the DOM, inside the
$ionicModal -- but the directive is not executing. I see the view for the
autocompleter executing, but it just doesn't render.

On Fri, Sep 18, 2015 at 12:34 PM, Guy Brand <notifications@github.com>
wrote:

> Hmm...what kind of Ionic package do you use? The latest official version
> of Ionic is 1.1.0 (see https://github.com/driftyco/ionic/releases) and
> you will need to use this version. And the element tag ion-autocomplete
> is not working anymore you need to use it as attribute as this was removed
> from 0.3.0 and you can remove the multiple-select="true" attribute too.
> Please also have a look at the release notes:
> https://github.com/guylabs/ion-autocomplete/blob/master/RELEASENOTES.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141501349>
> .
>



-- 
->|-

**Comment by guylabs** [comment]
Well then you need to upgrade to Ionic `1.1.0` and then try again. As `0.3.0` is using feature of Angular 1.4 and therefore this won't work with `1.0.1` of Ionic.

**Comment by Diodeus** [comment]
Guy, thanks for the update. I'll see if I can get the team to upgrade ionic.

On Sat, Sep 19, 2015 at 11:53 AM, Guy Brand <notifications@github.com>
wrote:

> Well then you need to upgrade to Ionic 1.1.0 and then try again. As 0.3.0
> is using feature of Angular 1.4 and therefore this won't work with 1.0.1
> of Ionic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141682912>
> .
>



-- 
->|-

**Comment by Diodeus** [comment]
Hi Guy, we have upgraded to Ionic 1.1.0, including angular 1.4 and continue
to see that same issue as described here (
https://github.com/guylabs/ion-autocomplete/issues/74)

The directive does not seem to execute. I just see the template directive
in the output. No errors.


"devDependencies": {
    "ionic": "driftyco/ionic-bower#1.1.0",
    "ui-router-extras": "~0.0.14",
    "ngCordova": "~0.1.17-alpha",
    "angular-ui-router": "~0.2.15",
    "angular-storage": "~0.5.0",
    "ion-autocomplete": "~0.3.0",
    "ion-sticky": "~1.0.3",
    "angular-ui-mask": "~1.4.1",
    "textAngular":"fraywing/textAngular#1.4.1"
  }

On Sat, Sep 19, 2015 at 11:53 AM, Guy Brand <notifications@github.com>
wrote:

> Well then you need to upgrade to Ionic 1.1.0 and then try again. As 0.3.0
> is using feature of Angular 1.4 and therefore this won't work with 1.0.1
> of Ionic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-141682912>
> .
>



-- 
->|-

**Comment by guylabs** [comment]
Hi,

do you use an custom template? And please use the master to test the latest state as the `0.3.0` version doesn't has all the fixes etc. Could you maybe test again with the master?

Thanks a lot and sorry for the late response,

Guy

**Comment by Diodeus** [comment]
Yes. I am using a custom template. I'll give it a try on Friday.

On Thu, Oct 8, 2015 at 2:45 PM, Guy Brand <notifications@github.com> wrote:

> Hi,
>
> do you use an custom template? And please use the master to test the
> latest state as the 0.3.0 version doesn't has all the fixes etc. Could
> you maybe test again with the master?
>
> Thanks a lot and sorry for the late response,
>
> Guy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guylabs/ion-autocomplete/issues/63#issuecomment-146650768>
> .
>



-- 
->|-

**Comment by guylabs** [comment]
Ok nice. And please also have a look at this comment: https://github.com/guylabs/ion-autocomplete/issues/70#issuecomment-139130782 as you will need that when using the master.

**Comment by guylabs** [comment]
Hi,

any news on this? I want to release `0.3.1` and I need to close the pending issues.

Thanks and regards,

Guy
