### ISSUE TITLE
Using textarea instead of input

### ISSUE THREAD

**Issue by jtbdevelopment** [guylabs/ion-autocomplete#68]
The app I have been using this on is getting close to ready, and one thing I note is that the input box used to display the chosen items can be a bit small (especially on smaller phones).  My list is a list of names, and it quickly runs into ellipses continuation after 1 1/2 names on an iphone 5 screen for example.

One idea I was toying with and did an ugly prototype was switching to a textarea object (which allows you to also set rows).  Would there be interest in this, or  more general interest in being able to replace the summary display template somehow (like how you can customize the popup template)?  

No promises - but I am more likely to look into it if there would be potential interest in merging it back in if it comes out decently.

**Comment by guylabs** [comment]
Hi,

well you can also use the directive with the attribute type and therefore I think it should run with the following sample too:

```javascript
<textarea ion-autocomplete 
    ng-model="model"
    ...
</textarea>
```

I just tested it in Codepen and it worked. So could you maybe try this and give me feedback?

If this is working for you then I think this should be added to the documentation as an example.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

are there any news on this? You can always reopen the issue if there is something more.

Thanks and regards,

Guy

**Comment by jtbdevelopment** [comment]
sorry been busy with something else - it seems a likely solution.  I'll come back if not.   thanks for the suggestion, I hadn't thought I could do that.
