### ISSUE TITLE
attribute and element type directive not working...

### ISSUE THREAD

**Issue by itree** [guylabs/ion-autocomplete#7]
Hi, 

 I was able to get "usage with the element restriction" working.  

However, I cannot get "the attribute and element type directive" working. 

This is what I put in my html:
<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete ng-valid ng-touched" autocomplete="off" ng-model="model" multiple-select="true" items-method="callbackMethod(query)">

Just wonder if it is a know bug, or am I doing something in correctly. 

Thanks for making the plugin, BTW.

**Comment by guylabs** [comment]
Hi,

yes that is not working with the 0.2.0 version. This feature is part of the 0.2.1 version which is released this weekend. But you can already use the latest master version. You can add it the following way:

```javascript
bower install --save-dev 'https://github.com/guylabs/ion-autocomplete.git#master'
```

The related issue is this one: https://github.com/guylabs/ion-autocomplete/issues/5

I hope with this it works as expected. If it does please close the issue and if not comment what is not working.

You see an example here: https://github.com/guylabs/ion-autocomplete#usage

Thanks and regards,

Guy

**Comment by itree** [comment]
ah for sure thank.
