### ISSUE TITLE
templateUrl not working

### ISSUE THREAD

**Issue by kachitta** [guylabs/ion-autocomplete#70]
After you added `randomCssClass` in 43a00b6, templateUrl stopped working because my own template can't access that class.

**Comment by guylabs** [comment]
Hi Kate, 

yes you are right. I just added the `randomCssClass` to the controller such that you can access it in your template with the following expression: `{{viewModel.randomCssClass}}`. 

I hope this solves your problem. Can you please test it and come back to me such that I can close the issue?

Thanks for reporting it!

Regards,

Guy

**Comment by kachitta** [comment]
Thanks Guy, it's working fine now. I will experiment more with custom templates and let you know if anything other comes up.
Oh, and it seems you forgot to remove a testing binding [here](https://github.com/guylabs/ion-autocomplete/commit/a239ea4ea58f8aaae2716bbcace2f714a734573d#diff-6d3fe8b4bd61849646c057a7eaae3dceR70).

**Comment by guylabs** [comment]
Ok great. Thanks for mentioning it with the test binding. Forgot to rebuild again ;).

Regards,

Guy

**Comment by kachitta** [comment]
Another issue came up: seems like `link` function is run just before `{{viewModel.randomCssClass}}` gets binded, so both `searchInputElement` and Done button are not found. Adding a tick `$timeout(fn);` before querying for them helped.

**Comment by kachitta** [comment]
OK, it did help just for a short time, it's not working now even with a tick timeout. Seems like there is a race between compiling template and running `link` function, which makes looking for elements in `link` function unreliable.
Maybe you can use delegated event for Done button and query for the search input in `showModal` method?
