### ISSUE TITLE
Issue with floating labels

### ISSUE THREAD

**Issue by lskuamoto** [guylabs/ion-autocomplete#77]
Hi,

I was trying to use the ion-autocomplete directive with floating labels from ionic and I could not make it work.

It seems that when we have use the class 'item-floating-label' the returned value is an object and not the value of the object property.

Code pen with issue: http://codepen.io/anon/pen/PPNJXB

Thanks

**Comment by guylabs** [comment]
Hi,

I just checked your code pen and it looks that there is an issue with the floating labels. I will try to fix it but it looks like a timing issue with the floating label when the value is added by the formatter of the `ng-model` controller.

Thanks and regards,

Guy

**Comment by lskuamoto** [comment]
Hi,

Thanks for the feedback!

I could make it work changing the line 153 from ion-autocomplete.js from

ngModelController.$setViewValue(ionAutocompleteController.selectedItems);

to:

ngModelController.$setViewValue(ionAutocompleteController.getItemValue(ionAutocompleteController.selectedItems, ionAutocompleteController.itemViewValueKey));

But now it works only when I have a floating label.

**Comment by guylabs** [comment]
Hi @lskuamoto,

sorry for my late reply but I found the solution. Please try the following snippet as there I added the `ng-class="{'has-input': model}"` to the `<span>` tag which then shows the label when you select the first item.

```html
<label class="item item-input item-floating-label">
    <span class="input-label" ng-class="{'has-input': model}">Multiple select autocomplete</span>
    <input ion-autocomplete .../>
</label>
```

Can you please verify and if it works for you then I will add this solution to the documentation.

Thanks and regards,

Guy

**Comment by lskuamoto** [comment]
Hi Guy,

Thanks for the reply.
It seems to work when the 

> ng-class="{'has-input': model}"

 is set.

Thanks!
