### ISSUE TITLE
How dynamic change placeholder and others labels

### ISSUE THREAD

**Issue by MrPro100** [guylabs/ion-autocomplete#78]
<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete truncate" autocomplete="off" max-selected-items="1"
                           ng-model="vm.userCity"
                           item-value-key="id"
                           item-view-value-key="text"
                           multiple-select="false"
                           placeholder="{{PLACEHOLDER' | translate}}"
                           cancel-label="{{vm.test}}"
                           select-items-label="{{'PLACEHOLDER_SEARCH' | translate}}"
                           select-item-label="{{'PLACEHOLDER_SEARCH' | translate}}"
                           template-url="js/core/search/search.html"
                           loading-icon="ios-small"
                           items-method=" vm.searchCity(query)"
                           items-clicked-method="vm.selectCity(callback)" />

Model binding not workin (((

**Comment by guylabs** [comment]
Hi Anatoliy,

can you please show me your issue reproducible based on this Codepen http://codepen.io/guylabs/pen/GJmwMw ? I cannot help you otherwise.

Thanks and regards,

Guy

**Comment by jianbo** [comment]
Missing this? 

                this.placeholder = valueOrDefault($attrs.placeholder, undefined);

**Comment by jianbo** [comment]
This works after I update the ionic.bundle.js to the codepen version, but local version breaks with ionic 1.1.0 and angular 1.4.3, project build using ionic-yeoman. any idea why?

**Comment by guylabs** [comment]
Hi,

@MrPro100 This is fixed in #76 such that your code should now work.
@jianbo You need to get the master as there #76 and some other things are fixed. `0.3.1` will be released when all issues are solved. Please create a new issue with a detailed description of what is not working and what your project setup is and how you use the component. Otherwise I cannot help you.

Thanks and regards,

Guy

**Comment by MrPro100** [comment]
Thanks
