### ISSUE TITLE
How to use a custom template

### ISSUE THREAD

**Issue by JunkMyFunk** [guylabs/ion-autocomplete#79]
When trying to use a custom template, nothing is shown when selecting the input. The default template used in `ion-autocomplete.js` includes a class in the wrapper div `randomCssClass` that is used later to show/hide the modal. When using a custom template, I can't see how I can set this class on my own wrapper div so that the component can use it.

**Comment by guylabs** [comment]
Hi,

please have a look at #70 as there this is fixed. You are able to get this `randomCssClass` over the `{{viewModel.randomCssClass}}` in your template.

I will then close this as duplicate.

Thanks and regards,

Guy
