### ISSUE TITLE
Does not close using Android back button

### ISSUE THREAD

**Issue by texh** [guylabs/ion-autocomplete#8]
Hi Guy, awesome work so far!

I've noticed that using the Android back button while the autocomplete modal screen is showing does not close the auto complete box, but does navigate back thru the history beneath the modal.

Not sure if I've missed something.

Jarrod

**Comment by guylabs** [comment]
Hi Jarrod,

thanks for mentioning this. There is already an issue in the ion-google-place project (https://github.com/israelidanny/ion-google-place/pull/18) and I will try to integrate this into the ion-autocomplete.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Well can we close this issue then as I've merged your pull request? I will release the 0.2.1 this weekend.

**Comment by texh** [comment]
Sounds like a plan provided you're happy with how it looks. Varies from israelidanny#18 solution but should achieve the same outcome.

**Comment by guylabs** [comment]
Well it's even clearer and easier to understand compared to the other solution ;). Thanks again!
