### ISSUE TITLE
Prefilled Items lead to unexpected behaviour

### ISSUE THREAD

**Issue by thedanielhanke** [guylabs/ion-autocomplete#81]
hi @guylabs,

i just found something strage in 0.3.1:

```coffee
# having resolved resources..
$stateProvider.state('tab.interests',
    resolve:
      interests: ->
        [
          { id: 1, name:'A' }
          { id: 2, name:'B' }
          { id: 3, name:'C' }
          { id: 4, name:'D' }
          { id: 5, name:'E' }
          { id: 6, name:'F' }
          { id: 7, name:'G' }
          { id: 8, name:'H' }
          { id: 9, name:'I' }
          { id: 10, name:'J' }
          { id: 11, name:'K' }
          { id: 12, name:'L' }
# -----------  magic barrier
#         { id: 13, name:'M' }
#         { id: 14, name:'N' }
#         { id: 15, name:'O' }
#         { id: 16, name:'P' }

# and the controller

app.controller 'InterestsCtrl', ($scope,interests) ->
  $scope.interests = interests
  $scope.filterInteresets = (query) -> interests
  $scope.selected_interests = []
```

as well as the input:

```html 
<input ion-autocomplete
                  type="text"
                  readonly="readonly"
                  class="ion-autocomplete"
                  autocomplete="off"
                  ng-model="selected_interests"
                  max-selected-items="3"
                  item-value-key="id"
                  item-view-value-key="name"
                  search-items="interests"
                  />
```

having the items 13 - 16 commted out, everything works fine. 
However, adding the 13th item, or more, that id is always preselected when i start tapping on the item.

any idea?

**Comment by thedanielhanke** [comment]
Aaah! :D found id! the mouse-position is just at that line when i click on the input.

so even by holding the mouse-key pressed, i get the f irst selected. the ng-click `$event` does not provide any information about the original target. checked on mobile (android), here it acts as i expect it to act. 

maybe usefull for you to just know it, in case of further questions regarding this behavioud.

Cheers.

**Comment by guylabs** [comment]
Hi Daniel,

thanks for pointing this out! I never had this issue as I do not use the `search-items` property in my project.

Thanks and regards,

Guy
