### ISSUE TITLE
When selecting item the window closes

### ISSUE THREAD

**Issue by Hesesses** [guylabs/ion-autocomplete#83]
Filtering etc works as it should, but when I click on item the window is closed and I cant select multiple items.

This is my code:
```
<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete" autocomplete="off"
            ng-model="model" 
            item-value-key="name"
            item-view-value-key="name"
            items-method="showTags(query)"
            items-method-value-key=""
            placeholder="Enter tags.."
            items-clicked-method="itemsClicked(callback)"
            items-removed-method="itemsRemoved(callback)"
            
             />
```

EDIT:
when using this everything works: 
https://rawgit.com/guylabs/ion-autocomplete/master/src/ion-autocomplete.js

```bower install ion-autocomplete --save ```
gives you 0.3.0 version which doesnt work

**Comment by guylabs** [comment]
Hi,

yes on the master some things are changed and I will release `0.3.1` as soon as all other issues are tested by the reporters. So then can you please use the master version or wait for `0.3.1`?

I will then close the issue as soon as `0.3.1` is released.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi,

any news on this? I need to release 0.3.1 soon such that I can finish off some issues.

Thanks and regards,

Guy

**Comment by Hesesses** [comment]
Hi,
master version fixes this
