### ISSUE TITLE
ng-model = [null]

### ISSUE THREAD

**Issue by Hesesses** [guylabs/ion-autocomplete#84]
I'm using ng-model="article.data.tags" 
When I select items the component shows "tag, tag2, tag3" and it is saved to localstorage as: 
"tags": ["tag","tag2","tag3"]
No problems here.

After reloading the page
the component changes ng-model value to [null]

Any ideas how to fix this?

```
<input ion-autocomplete type="text" readonly="readonly" class="ion-autocomplete" autocomplete="off"
            ng-model="article.data.tags" 
            item-value-key="name"
            item-view-value-key="name"
            items-method="showTags(query)"
            items-method-value-key=""
            placeholder="Enter tags.."
            items-clicked-method="itemsClicked(callback)"
            items-removed-method="itemsRemoved(callback)"
/>
```

**Comment by thedanielhanke** [comment]
https://github.com/guylabs/ion-autocomplete#the-model-to-item-method

**Comment by guylabs** [comment]
@thedanielhanke Thanks for the answer! Really appreciated!

**Comment by thedanielhanke** [comment]
:+1:
