### ISSUE TITLE
List not populating on iOS emulator 

### ISSUE THREAD

**Issue by satishkunisi** [guylabs/ion-autocomplete#87]
Hi, the autocomplete populates and filters correctly when debugging in Chrome but when I try to use the iOS emulator the list doesn't populate. Any ideas on what I might be doing wrong? Thanks!

**Comment by guylabs** [comment]
Hi Satish,

well I am not using iOS and therefore I cannot test it. But on the mobile itself it works properly? So you say that the modal is not shown or the `items-method` is not called?

Thanks and sorry for the late response,

Guy

**Comment by satishkunisi** [comment]
No worries Guy. I'll test on device soon and update the issue.

**Comment by thedanielhanke** [comment]
@satishkunisi you can connect your safari the the emulated ios browser and check error messages - would still be helpfull to know the issues.

**Comment by guylabs** [comment]
Hi Satish,

any news here?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Satish,

I close this issue now due to inactivity. You can always reopen it if you want.

Thanks and regards,

Guy
