### ISSUE TITLE
When pre-populating the select-items-label value is ignored

### ISSUE THREAD

**Issue by jswann** [guylabs/ion-autocomplete#88]
When I'm pre-populating the list, the value of the select-items-label is ignored. If i remove the items from the list my selected label is used.

**Comment by guylabs** [comment]
Hi Josh,

could you maybe create a reproducible codepen such that I can have a look at it? This way it is hard to reproduce as I cannot guess your configuration and with a codepen this is isolated and easily reproducible.

Thanks and sorry for the late response,

Guy

**Comment by thedanielhanke** [comment]
cannot confirm. 
```
'<ion-item class="item-divider" ng-show="viewModel.searchItems.length > 0">{{viewModel.selectItemsLabel}}</ion-item>',
```
the opposite should be the case?

**Comment by jswann** [comment]
My apologizes for the delay as well. 

I had resolved this issue while overriding the default template with my own. As I tried to recreate using the default template, I was unable to recreate. I suspect I had erroneously seen this "defect" while transitioning from the default template to my own. 

My apologizes for the false positive and I really do appreciate the work you've done in this component.

**Comment by guylabs** [comment]
Hi Josh,

ok nice that it works now :).

Thanks and regards,

Guy
