### ISSUE TITLE
Enhancement: updating the viewValue on demand

### ISSUE THREAD

**Issue by thedanielhanke** [guylabs/ion-autocomplete#90]
Hi @guylabs ,

in my app it comes to a special situation:

- Autocomplete: select an item
- item is shown
- other controller / service changes that items name
- autocomplete still shows the old name.

if just did an really ugly hack to workaround like this:

```javascript
ionAutocompleteController.redraw = function() {
     ngModelController.$setViewValue(ionAutocompleteController.selectedItems);
     ngModelController.$render();
};
``` 
and calling it via $emit when the item is changed. 

in short: having a way to tell the Controller to redraw without braodcasting/emitting would be nice.

So not sure of that functionality actually IS given, and i just got a bug.. :)

**Comment by guylabs** [comment]
Hi Daniel,

could you maybe have a look at the #89 issue because this is the way to prepopulate/change or clear the selected items.

Thanks and regards,

Guy

**Comment by thedanielhanke** [comment]
@guylabs ah an update. thanks. will check.

**Comment by thedanielhanke** [comment]
@guylabs so i updated to latest master version.

1) it migt be worthy to note that external-model must not be the same binding as ng-model. else you get nice loops while prepolutin ;)

2) works fine for for both, arrays and strings, nice :+1:

3) did not help in this case.

The case is:
i use the google-places-autocomplete-api to get some city-names while typing ahead. pretty common, works fine when selecting.
now imagine you select 'Basel', ng-model value becomes e.h.
```{ place_id: 'google hash', name: 'Basel'} ```
after saving and editing, i can assign:

```html
ng-model="model.location"
external-model="defaults.location"
model-to-item-method="resolve_location(modelValue)"
```
and
```coffee
$scope.defaults =
   location:
      name: model.location.name
      id: model.location.id

$scope.resolve_location = (modelValue) -> $scope.defaults.location
```
this leads to have the items preselected and visible. fine.
now, when `$scope.defaults.locatiion.name` changes(*), the resolve_location method prevents me from having visible updates.

changing it like:

```coffee
          if $scope.defaults.location.name is modelValue
            $scope.defaults.location
          else # fake-model
            name: modelValue
            id: modelValue
```
and applying changes to the `defaults.location.name` property leads to the updates however.

Well now this (my) code already is bad, and seems like i am on the wrong road. i know my case might be special, but changing model names is not that unusual, right? any suggestions? if you think that is too special, please say so -  i am fine with it an will create some hackarounds to be able to update the plugin.


*= you might wonder why 'Basel' itself should change.  The reason is, that after selectig Basel, the user can specify some more details via google maps by tapping on a street, e.h. 'St. Alban-Anlage' - in that case i want to display the GPS-Location as selected value. so i really do want to overwrite the current models name. 'Basel' and 'Alban..' were choosen randomly ;P

**Comment by thedanielhanke** [comment]
ok fixed. duh!  external-model='model.location.name' with ng-model='model.location' did the trick. thanks!

**Comment by guylabs** [comment]
@thedanielhanke ok great that it worked this way.

Thanks and regards,

Guy
