### ISSUE TITLE
collection repeat is not refreshing properly

### ISSUE THREAD

**Issue by makraade** [guylabs/ion-autocomplete#94]
Hi,

I am not sure if there is a problem with the ionAutocomplete directive or with the ionic framework itself but i have the problem that the collection repeat is not refreshing properly when searching an spotify artist.

Its difficult to explain but please try the codepen example and search for "LaBrassBanda".
http://codepen.io/makraade/pen/vNegLa?editors=101

![ion-autocomplete](https://cloud.githubusercontent.com/assets/15126944/10490931/f4418f9c-72a3-11e5-9c32-4f9a2f6021c4.png)

Spotify Web API delivers the correct 2 Objects (see console or screenshot), but in the collection repeat the second item is something different... Now try to drag the item or click on it => collection repeat gets refreshed with the correct value. (LaBrassBanda & Coconami)

I thought  $ionicScrollDelegate.resize(); would help but it didnt.

Do you have any idea?

Best Regards,
Markus

**Comment by maltalk** [comment]
Only happens in safari / ios.

**Comment by guylabs** [comment]
Hi Markus,

maybe Ionic has the same behavior. See #101 as this one was also in the ionic collection. Could you try the example without the `ion-autocomplete` module and just with a collection repeat?

Thanks and regards,

Guy

**Comment by maltalk** [comment]
Hi again,

Just tried with ng-repeat instead of collection repeat (custom template).
Still the same behavior as collection-repeat.

Regards,

**Comment by guylabs** [comment]
Hi @maltalk,

ok and this only happens when you test in Safari or on iOS right? Did you already check the issues from Ionic if there is already one created? Because I cannot reproduce it in Chrome or in Safari (9.0.1 (11601.2.7.2)) on OSX 10.11.1.

For me the codepen always returns the proper two values right away.

Thanks and regards,

Guy

**Comment by maltalk** [comment]
Hi Guy,

The console shows the right results but the view doesnt.

Safari 9.0.1 (11601.2.7.2)
OSX 10.11.1

Here is the gif reproducing the error:
http://gfycat.com/EasygoingRegalIcterinewarbler

And no, didn't check the ionic issues already, sorry.

Thanks and regards,

**Comment by guylabs** [comment]
Hi @maltalk,

could you come back if you checked the Ionic issues for a similar issue? Because I cannot reproduce it locally and therefore cannot help you out right now.

Thanks and regards,

Guy

**Comment by UBICX** [comment]
hi 
i have the same issue : the list is not refresh but in the source code i have the cood value!

![capture d ecran 2015-12-09 a 15 48 14](https://cloud.githubusercontent.com/assets/6323653/11688351/5c61cd62-9e8c-11e5-9701-06ef2d072bb4.png)

**Comment by guylabs** [comment]
Hi @UBICX,

what is your environment in which you test? And did you already tested it with a standard Ionic example?

Thanks and regards,

Guy

**Comment by UBICX** [comment]
hi

a use it in ionic project
"dependencies": {
    "underscore": "~1.8.3",
    "ngmap": "~1.9.0",
    "angular-moment": "~0.10.1",
    "angular-resource": "~1.3.11",
    "ngCordova": "~0.1.17-alpha",
    "angular-slugify": "williamboman/angular-slugify",
    "ionic-contrib-tinder-cards": "*",
    "bourbon": "~4.2.3",
    "angular-youtube-mb": "~1.1.0",
    "ion-autocomplete": "~0.3.1",
    "ionic-datepicker": "~0.9.0"
  },
  "resolutions": {
    "angular": "~1.4.7"
  }

i have the same issue on safari and iOS, android app
when i click on a row the real value appear !
when i resize my browser : i see my real list
i test my code with this code http://codepen.io/makraade/pen/vNegLa?editors=101
and i have the same issue in my project.

regards
Fabien

Le 9 déc. 2015 à 15:54, Guy Brand <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @UBICX<https://github.com/UBICX>,

what is your environment in which you test? And did you already tested it with a standard Ionic example?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
@UBICX What kind of Ionic version do you use in your project? Can you use the master version of the `ion-autocomplete` component and use the `1.1.1` version of Ionic and then try again? I am not able to reproduce the issue in any way.

**Comment by guylabs** [comment]
Hi,

due to inactivity I will close the issue. If you still have any issues or remarks please add a comment or reopen the issue.

Thanks and regards,

Guy
