### ISSUE TITLE
minified version not working

### ISSUE THREAD

**Issue by Screeze** [guylabs/ion-autocomplete#95]
When I first tried to use the module, I tried to include the ion-autocomplete.min.js from the bower package in the index.html. This didn't work due to the error:

Error: [$injector:unpr] Unknown provider: aProvider <- a
The stacktrace was not very helpfully in that case.

After a lot of debugging without a clue what's going wrong, I tried to use the unminified version - and it worked.

So it seems like the minified version in the bower package is not working as expected?

**Comment by guylabs** [comment]
Hi Ralf,

thanks for reporting it! This is fixed in the master with the #93 pull request. I will close the issue now and if it is not working please reopen it.

Thanks and regards,

Guy
