### ISSUE TITLE
Change the location of suggested options

### ISSUE THREAD

**Issue by mohitgupta86** [guylabs/ion-autocomplete#97]
Hi

Location of suggested option comes at the bottom of the already selected items. Can we bring it to the top somehow, that will  be better since I have a long list selected then I have to scroll down to the bottom to make the selections every time.
Any quick fix / workaround would be appreciated

Thanks

**Comment by guylabs** [comment]
Hi @mohitgupta86,

you can create your own template according to this documentation: https://github.com/guylabs/ion-autocomplete#template-url There you are able to change everything and you can design the modal as you need it. You just need to keep all the classes such that the component finds the needed buttons and inputs etc.

There are no plans to change this in the master so I will close the issue. If you have any questions regarding the custom template, feel free to ask within a comment.

Thanks and regards,

Guy
